ootEnumRoomShapeType = [
    # ("Custom", "Custom", "Custom"),
    ("ROOM_SHAPE_TYPE_NORMAL", "Normal", "Normal"),
    ("ROOM_SHAPE_TYPE_IMAGE", "Image", "Image"),
    ("ROOM_SHAPE_TYPE_CULLABLE", "Cullable", "Cullable"),
]

ootRoomShapeStructs = {
    "ROOM_SHAPE_TYPE_NORMAL": "RoomShapeNormal",
    "ROOM_SHAPE_TYPE_CULLABLE": "RoomShapeCullable",
}

ootRoomShapeEntryStructs = {
    "ROOM_SHAPE_TYPE_NORMAL": "RoomShapeDListsEntry",
    "ROOM_SHAPE_TYPE_CULLABLE": "RoomShapeCullableEntry",
}

ootEnumSceneMenu = [
    ("General", "General", "General"),
    ("Lighting", "Lighting", "Lighting"),
    ("Cutscene", "Cutscene", "Cutscene"),
    ("Exits", "Exits", "Exits"),
    ("Alternate", "Alternate", "Alternate"),
]

ootEnumRenderScene = [
    ("General", "General", "General"),
    ("Alternate", "Alternate", "Alternate"),
]

ootEnumSceneMenuAlternate = [
    ("General", "General", "General"),
    ("Lighting", "Lighting", "Lighting"),
    ("Cutscene", "Cutscene", "Cutscene"),
]

ootEnumRoomMenu = [
    ("General", "General", "General"),
    ("Objects", "Objects", "Objects"),
    ("Alternate", "Alternate", "Alternate"),
]

ootEnumRoomMenuAlternate = [
    ("General", "General", "General"),
    ("Objects", "Objects", "Objects"),
]

ootEnumHeaderMenu = [
    ("Child Night", "Child Night", "Child Night"),
    ("Adult Day", "Adult Day", "Adult Day"),
    ("Adult Night", "Adult Night", "Adult Night"),
    ("Cutscene", "Cutscene", "Cutscene"),
]

ootEnumLightGroupMenu = [
    ("Dawn", "Dawn", "Dawn"),
    ("Day", "Day", "Day"),
    ("Dusk", "Dusk", "Dusk"),
    ("Night", "Night", "Night"),
]

ootEnumTransitionActorID = [
    ("Custom", "Custom", "Custom"),
    ("ACTOR_EN_DOOR", "EN_DOOR", "EN_DOOR"),
    ("ACTOR_DOOR_SHUTTER", "DOOR_SHUTTER", "DOOR_SHUTTER"),
    ("ACTOR_DOOR_WARP1", "DOOR_WARP1", "DOOR_WARP1"),
    ("ACTOR_DOOR_TOKI", "DOOR_TOKI", "DOOR_TOKI"),
    ("ACTOR_DOOR_ANA", "DOOR_ANA", "DOOR_ANA"),
    ("ACTOR_DOOR_GERUDO", "DOOR_GERUDO", "DOOR_GERUDO"),
    ("ACTOR_DOOR_KILLER", "DOOR_KILLER", "DOOR_KILLER"),
]

ootEnumActorID = [
    ("Custom", "Custom", "Custom"),
    ("ACTOR_PLAYER", "PLAYER", "PLAYER"),
    ("ACTOR_EN_TEST", "EN_TEST", "EN_TEST"),
    ("ACTOR_EN_GIRLA", "EN_GIRLA", "EN_GIRLA"),
    ("ACTOR_EN_PART", "EN_PART", "EN_PART"),
    ("ACTOR_EN_LIGHT", "EN_LIGHT", "EN_LIGHT"),
    ("ACTOR_EN_DOOR", "EN_DOOR", "EN_DOOR"),
    ("ACTOR_EN_BOX", "EN_BOX", "EN_BOX"),
    ("ACTOR_BG_DY_YOSEIZO", "BG_DY_YOSEIZO", "BG_DY_YOSEIZO"),
    ("ACTOR_BG_HIDAN_FIREWALL", "BG_HIDAN_FIREWALL", "BG_HIDAN_FIREWALL"),
    ("ACTOR_EN_POH", "EN_POH", "EN_POH"),
    ("ACTOR_EN_OKUTA", "EN_OKUTA", "EN_OKUTA"),
    ("ACTOR_BG_YDAN_SP", "BG_YDAN_SP", "BG_YDAN_SP"),
    ("ACTOR_EN_BOM", "EN_BOM", "EN_BOM"),
    ("ACTOR_EN_WALLMAS", "EN_WALLMAS", "EN_WALLMAS"),
    ("ACTOR_EN_DODONGO", "EN_DODONGO", "EN_DODONGO"),
    ("ACTOR_EN_FIREFLY", "EN_FIREFLY", "EN_FIREFLY"),
    ("ACTOR_EN_HORSE", "EN_HORSE", "EN_HORSE"),
    ("ACTOR_EN_ITEM00", "EN_ITEM00", "EN_ITEM00"),
    ("ACTOR_EN_ARROW", "EN_ARROW", "EN_ARROW"),
    ("ACTOR_EN_ELF", "EN_ELF", "EN_ELF"),
    ("ACTOR_EN_NIW", "EN_NIW", "EN_NIW"),
    ("ACTOR_EN_TITE", "EN_TITE", "EN_TITE"),
    ("ACTOR_EN_REEBA", "EN_REEBA", "EN_REEBA"),
    ("ACTOR_EN_PEEHAT", "EN_PEEHAT", "EN_PEEHAT"),
    ("ACTOR_EN_BUTTE", "EN_BUTTE", "EN_BUTTE"),
    ("ACTOR_EN_INSECT", "EN_INSECT", "EN_INSECT"),
    ("ACTOR_EN_FISH", "EN_FISH", "EN_FISH"),
    ("ACTOR_EN_HOLL", "EN_HOLL", "EN_HOLL"),
    ("ACTOR_EN_SCENE_CHANGE", "EN_SCENE_CHANGE", "EN_SCENE_CHANGE"),
    ("ACTOR_EN_ZF", "EN_ZF", "EN_ZF"),
    ("ACTOR_EN_HATA", "EN_HATA", "EN_HATA"),
    ("ACTOR_BOSS_DODONGO", "BOSS_DODONGO", "BOSS_DODONGO"),
    ("ACTOR_BOSS_GOMA", "BOSS_GOMA", "BOSS_GOMA"),
    ("ACTOR_EN_ZL1", "EN_ZL1", "EN_ZL1"),
    ("ACTOR_EN_VIEWER", "EN_VIEWER", "EN_VIEWER"),
    ("ACTOR_EN_GOMA", "EN_GOMA", "EN_GOMA"),
    ("ACTOR_BG_PUSHBOX", "BG_PUSHBOX", "BG_PUSHBOX"),
    ("ACTOR_EN_BUBBLE", "EN_BUBBLE", "EN_BUBBLE"),
    ("ACTOR_DOOR_SHUTTER", "DOOR_SHUTTER", "DOOR_SHUTTER"),
    ("ACTOR_EN_DODOJR", "EN_DODOJR", "EN_DODOJR"),
    ("ACTOR_EN_BDFIRE", "EN_BDFIRE", "EN_BDFIRE"),
    ("ACTOR_EN_BOOM", "EN_BOOM", "EN_BOOM"),
    ("ACTOR_EN_TORCH2", "EN_TORCH2", "EN_TORCH2"),
    ("ACTOR_EN_BILI", "EN_BILI", "EN_BILI"),
    ("ACTOR_EN_TP", "EN_TP", "EN_TP"),
    ("ACTOR_EN_ST", "EN_ST", "EN_ST"),
    ("ACTOR_EN_BW", "EN_BW", "EN_BW"),
    ("ACTOR_EN_A_OBJ", "EN_A_OBJ", "EN_A_OBJ"),
    ("ACTOR_EN_EIYER", "EN_EIYER", "EN_EIYER"),
    ("ACTOR_EN_RIVER_SOUND", "EN_RIVER_SOUND", "EN_RIVER_SOUND"),
    ("ACTOR_EN_HORSE_NORMAL", "EN_HORSE_NORMAL", "EN_HORSE_NORMAL"),
    ("ACTOR_EN_OSSAN", "EN_OSSAN", "EN_OSSAN"),
    ("ACTOR_BG_TREEMOUTH", "BG_TREEMOUTH", "BG_TREEMOUTH"),
    ("ACTOR_BG_DODOAGO", "BG_DODOAGO", "BG_DODOAGO"),
    ("ACTOR_BG_HIDAN_DALM", "BG_HIDAN_DALM", "BG_HIDAN_DALM"),
    ("ACTOR_BG_HIDAN_HROCK", "BG_HIDAN_HROCK", "BG_HIDAN_HROCK"),
    ("ACTOR_EN_HORSE_GANON", "EN_HORSE_GANON", "EN_HORSE_GANON"),
    ("ACTOR_BG_HIDAN_ROCK", "BG_HIDAN_ROCK", "BG_HIDAN_ROCK"),
    ("ACTOR_BG_HIDAN_RSEKIZOU", "BG_HIDAN_RSEKIZOU", "BG_HIDAN_RSEKIZOU"),
    ("ACTOR_BG_HIDAN_SEKIZOU", "BG_HIDAN_SEKIZOU", "BG_HIDAN_SEKIZOU"),
    ("ACTOR_BG_HIDAN_SIMA", "BG_HIDAN_SIMA", "BG_HIDAN_SIMA"),
    ("ACTOR_BG_HIDAN_SYOKU", "BG_HIDAN_SYOKU", "BG_HIDAN_SYOKU"),
    ("ACTOR_EN_XC", "EN_XC", "EN_XC"),
    ("ACTOR_BG_HIDAN_CURTAIN", "BG_HIDAN_CURTAIN", "BG_HIDAN_CURTAIN"),
    ("ACTOR_BG_SPOT00_HANEBASI", "BG_SPOT00_HANEBASI", "BG_SPOT00_HANEBASI"),
    ("ACTOR_EN_MB", "EN_MB", "EN_MB"),
    ("ACTOR_EN_BOMBF", "EN_BOMBF", "EN_BOMBF"),
    ("ACTOR_EN_ZL2", "EN_ZL2", "EN_ZL2"),
    ("ACTOR_BG_HIDAN_FSLIFT", "BG_HIDAN_FSLIFT", "BG_HIDAN_FSLIFT"),
    ("ACTOR_EN_OE2", "EN_OE2", "EN_OE2"),
    ("ACTOR_BG_YDAN_HASI", "BG_YDAN_HASI", "BG_YDAN_HASI"),
    ("ACTOR_BG_YDAN_MARUTA", "BG_YDAN_MARUTA", "BG_YDAN_MARUTA"),
    ("ACTOR_BOSS_GANONDROF", "BOSS_GANONDROF", "BOSS_GANONDROF"),
    ("ACTOR_EN_AM", "EN_AM", "EN_AM"),
    ("ACTOR_EN_DEKUBABA", "EN_DEKUBABA", "EN_DEKUBABA"),
    ("ACTOR_EN_M_FIRE1", "EN_M_FIRE1", "EN_M_FIRE1"),
    ("ACTOR_EN_M_THUNDER", "EN_M_THUNDER", "EN_M_THUNDER"),
    ("ACTOR_BG_DDAN_JD", "BG_DDAN_JD", "BG_DDAN_JD"),
    ("ACTOR_BG_BREAKWALL", "BG_BREAKWALL", "BG_BREAKWALL"),
    ("ACTOR_EN_JJ", "EN_JJ", "EN_JJ"),
    ("ACTOR_EN_HORSE_ZELDA", "EN_HORSE_ZELDA", "EN_HORSE_ZELDA"),
    ("ACTOR_BG_DDAN_KD", "BG_DDAN_KD", "BG_DDAN_KD"),
    ("ACTOR_DOOR_WARP1", "DOOR_WARP1", "DOOR_WARP1"),
    ("ACTOR_OBJ_SYOKUDAI", "OBJ_SYOKUDAI", "OBJ_SYOKUDAI"),
    ("ACTOR_ITEM_B_HEART", "ITEM_B_HEART", "ITEM_B_HEART"),
    ("ACTOR_EN_DEKUNUTS", "EN_DEKUNUTS", "EN_DEKUNUTS"),
    ("ACTOR_BG_MENKURI_KAITEN", "BG_MENKURI_KAITEN", "BG_MENKURI_KAITEN"),
    ("ACTOR_BG_MENKURI_EYE", "BG_MENKURI_EYE", "BG_MENKURI_EYE"),
    ("ACTOR_EN_VALI", "EN_VALI", "EN_VALI"),
    ("ACTOR_BG_MIZU_MOVEBG", "BG_MIZU_MOVEBG", "BG_MIZU_MOVEBG"),
    ("ACTOR_BG_MIZU_WATER", "BG_MIZU_WATER", "BG_MIZU_WATER"),
    ("ACTOR_ARMS_HOOK", "ARMS_HOOK", "ARMS_HOOK"),
    ("ACTOR_EN_FHG", "EN_FHG", "EN_FHG"),
    ("ACTOR_BG_MORI_HINERI", "BG_MORI_HINERI", "BG_MORI_HINERI"),
    ("ACTOR_EN_BB", "EN_BB", "EN_BB"),
    ("ACTOR_BG_TOKI_HIKARI", "BG_TOKI_HIKARI", "BG_TOKI_HIKARI"),
    ("ACTOR_EN_YUKABYUN", "EN_YUKABYUN", "EN_YUKABYUN"),
    ("ACTOR_BG_TOKI_SWD", "BG_TOKI_SWD", "BG_TOKI_SWD"),
    ("ACTOR_EN_FHG_FIRE", "EN_FHG_FIRE", "EN_FHG_FIRE"),
    ("ACTOR_BG_MJIN", "BG_MJIN", "BG_MJIN"),
    ("ACTOR_BG_HIDAN_KOUSI", "BG_HIDAN_KOUSI", "BG_HIDAN_KOUSI"),
    ("ACTOR_DOOR_TOKI", "DOOR_TOKI", "DOOR_TOKI"),
    ("ACTOR_BG_HIDAN_HAMSTEP", "BG_HIDAN_HAMSTEP", "BG_HIDAN_HAMSTEP"),
    ("ACTOR_EN_BIRD", "EN_BIRD", "EN_BIRD"),
    ("ACTOR_EN_WOOD02", "EN_WOOD02", "EN_WOOD02"),
    ("ACTOR_EN_LIGHTBOX", "EN_LIGHTBOX", "EN_LIGHTBOX"),
    ("ACTOR_EN_PU_BOX", "EN_PU_BOX", "EN_PU_BOX"),
    ("ACTOR_EN_TRAP", "EN_TRAP", "EN_TRAP"),
    ("ACTOR_EN_AROW_TRAP", "EN_AROW_TRAP", "EN_AROW_TRAP"),
    ("ACTOR_EN_VASE", "EN_VASE", "EN_VASE"),
    ("ACTOR_EN_TA", "EN_TA", "EN_TA"),
    ("ACTOR_EN_TK", "EN_TK", "EN_TK"),
    ("ACTOR_BG_MORI_BIGST", "BG_MORI_BIGST", "BG_MORI_BIGST"),
    ("ACTOR_BG_MORI_ELEVATOR", "BG_MORI_ELEVATOR", "BG_MORI_ELEVATOR"),
    ("ACTOR_BG_MORI_KAITENKABE", "BG_MORI_KAITENKABE", "BG_MORI_KAITENKABE"),
    ("ACTOR_BG_MORI_RAKKATENJO", "BG_MORI_RAKKATENJO", "BG_MORI_RAKKATENJO"),
    ("ACTOR_EN_VM", "EN_VM", "EN_VM"),
    ("ACTOR_DEMO_EFFECT", "DEMO_EFFECT", "DEMO_EFFECT"),
    ("ACTOR_DEMO_KANKYO", "DEMO_KANKYO", "DEMO_KANKYO"),
    ("ACTOR_BG_HIDAN_FWBIG", "BG_HIDAN_FWBIG", "BG_HIDAN_FWBIG"),
    ("ACTOR_EN_FLOORMAS", "EN_FLOORMAS", "EN_FLOORMAS"),
    ("ACTOR_EN_HEISHI1", "EN_HEISHI1", "EN_HEISHI1"),
    ("ACTOR_EN_RD", "EN_RD", "EN_RD"),
    ("ACTOR_EN_PO_SISTERS", "EN_PO_SISTERS", "EN_PO_SISTERS"),
    ("ACTOR_BG_HEAVY_BLOCK", "BG_HEAVY_BLOCK", "BG_HEAVY_BLOCK"),
    ("ACTOR_BG_PO_EVENT", "BG_PO_EVENT", "BG_PO_EVENT"),
    ("ACTOR_OBJ_MURE", "OBJ_MURE", "OBJ_MURE"),
    ("ACTOR_EN_SW", "EN_SW", "EN_SW"),
    ("ACTOR_BOSS_FD", "BOSS_FD", "BOSS_FD"),
    ("ACTOR_OBJECT_KANKYO", "OBJECT_KANKYO", "OBJECT_KANKYO"),
    ("ACTOR_EN_DU", "EN_DU", "EN_DU"),
    ("ACTOR_EN_FD", "EN_FD", "EN_FD"),
    ("ACTOR_EN_HORSE_LINK_CHILD", "EN_HORSE_LINK_CHILD", "EN_HORSE_LINK_CHILD"),
    ("ACTOR_DOOR_ANA", "DOOR_ANA", "DOOR_ANA"),
    ("ACTOR_BG_SPOT02_OBJECTS", "BG_SPOT02_OBJECTS", "BG_SPOT02_OBJECTS"),
    ("ACTOR_BG_HAKA", "BG_HAKA", "BG_HAKA"),
    ("ACTOR_MAGIC_WIND", "MAGIC_WIND", "MAGIC_WIND"),
    ("ACTOR_MAGIC_FIRE", "MAGIC_FIRE", "MAGIC_FIRE"),
    ("ACTOR_EN_RU1", "EN_RU1", "EN_RU1"),
    ("ACTOR_BOSS_FD2", "BOSS_FD2", "BOSS_FD2"),
    ("ACTOR_EN_FD_FIRE", "EN_FD_FIRE", "EN_FD_FIRE"),
    ("ACTOR_EN_DH", "EN_DH", "EN_DH"),
    ("ACTOR_EN_DHA", "EN_DHA", "EN_DHA"),
    ("ACTOR_EN_RL", "EN_RL", "EN_RL"),
    ("ACTOR_EN_ENCOUNT1", "EN_ENCOUNT1", "EN_ENCOUNT1"),
    ("ACTOR_DEMO_DU", "DEMO_DU", "DEMO_DU"),
    ("ACTOR_DEMO_IM", "DEMO_IM", "DEMO_IM"),
    ("ACTOR_DEMO_TRE_LGT", "DEMO_TRE_LGT", "DEMO_TRE_LGT"),
    ("ACTOR_EN_FW", "EN_FW", "EN_FW"),
    ("ACTOR_BG_VB_SIMA", "BG_VB_SIMA", "BG_VB_SIMA"),
    ("ACTOR_EN_VB_BALL", "EN_VB_BALL", "EN_VB_BALL"),
    ("ACTOR_BG_HAKA_MEGANE", "BG_HAKA_MEGANE", "BG_HAKA_MEGANE"),
    ("ACTOR_BG_HAKA_MEGANEBG", "BG_HAKA_MEGANEBG", "BG_HAKA_MEGANEBG"),
    ("ACTOR_BG_HAKA_SHIP", "BG_HAKA_SHIP", "BG_HAKA_SHIP"),
    ("ACTOR_BG_HAKA_SGAMI", "BG_HAKA_SGAMI", "BG_HAKA_SGAMI"),
    ("ACTOR_EN_HEISHI2", "EN_HEISHI2", "EN_HEISHI2"),
    ("ACTOR_EN_ENCOUNT2", "EN_ENCOUNT2", "EN_ENCOUNT2"),
    ("ACTOR_EN_FIRE_ROCK", "EN_FIRE_ROCK", "EN_FIRE_ROCK"),
    ("ACTOR_EN_BROB", "EN_BROB", "EN_BROB"),
    ("ACTOR_MIR_RAY", "MIR_RAY", "MIR_RAY"),
    ("ACTOR_BG_SPOT09_OBJ", "BG_SPOT09_OBJ", "BG_SPOT09_OBJ"),
    ("ACTOR_BG_SPOT18_OBJ", "BG_SPOT18_OBJ", "BG_SPOT18_OBJ"),
    ("ACTOR_BOSS_VA", "BOSS_VA", "BOSS_VA"),
    ("ACTOR_BG_HAKA_TUBO", "BG_HAKA_TUBO", "BG_HAKA_TUBO"),
    ("ACTOR_BG_HAKA_TRAP", "BG_HAKA_TRAP", "BG_HAKA_TRAP"),
    ("ACTOR_BG_HAKA_HUTA", "BG_HAKA_HUTA", "BG_HAKA_HUTA"),
    ("ACTOR_BG_HAKA_ZOU", "BG_HAKA_ZOU", "BG_HAKA_ZOU"),
    ("ACTOR_BG_SPOT17_FUNEN", "BG_SPOT17_FUNEN", "BG_SPOT17_FUNEN"),
    ("ACTOR_EN_SYATEKI_ITM", "EN_SYATEKI_ITM", "EN_SYATEKI_ITM"),
    ("ACTOR_EN_SYATEKI_MAN", "EN_SYATEKI_MAN", "EN_SYATEKI_MAN"),
    ("ACTOR_EN_TANA", "EN_TANA", "EN_TANA"),
    ("ACTOR_EN_NB", "EN_NB", "EN_NB"),
    ("ACTOR_BOSS_MO", "BOSS_MO", "BOSS_MO"),
    ("ACTOR_EN_SB", "EN_SB", "EN_SB"),
    ("ACTOR_EN_BIGOKUTA", "EN_BIGOKUTA", "EN_BIGOKUTA"),
    ("ACTOR_EN_KAREBABA", "EN_KAREBABA", "EN_KAREBABA"),
    ("ACTOR_BG_BDAN_OBJECTS", "BG_BDAN_OBJECTS", "BG_BDAN_OBJECTS"),
    ("ACTOR_DEMO_SA", "DEMO_SA", "DEMO_SA"),
    ("ACTOR_DEMO_GO", "DEMO_GO", "DEMO_GO"),
    ("ACTOR_EN_IN", "EN_IN", "EN_IN"),
    ("ACTOR_EN_TR", "EN_TR", "EN_TR"),
    ("ACTOR_BG_SPOT16_BOMBSTONE", "BG_SPOT16_BOMBSTONE", "BG_SPOT16_BOMBSTONE"),
    ("ACTOR_BG_HIDAN_KOWARERUKABE", "BG_HIDAN_KOWARERUKABE", "BG_HIDAN_KOWARERUKABE"),
    ("ACTOR_BG_BOMBWALL", "BG_BOMBWALL", "BG_BOMBWALL"),
    ("ACTOR_BG_SPOT08_ICEBLOCK", "BG_SPOT08_ICEBLOCK", "BG_SPOT08_ICEBLOCK"),
    ("ACTOR_EN_RU2", "EN_RU2", "EN_RU2"),
    ("ACTOR_OBJ_DEKUJR", "OBJ_DEKUJR", "OBJ_DEKUJR"),
    ("ACTOR_BG_MIZU_UZU", "BG_MIZU_UZU", "BG_MIZU_UZU"),
    ("ACTOR_BG_SPOT06_OBJECTS", "BG_SPOT06_OBJECTS", "BG_SPOT06_OBJECTS"),
    ("ACTOR_BG_ICE_OBJECTS", "BG_ICE_OBJECTS", "BG_ICE_OBJECTS"),
    ("ACTOR_BG_HAKA_WATER", "BG_HAKA_WATER", "BG_HAKA_WATER"),
    ("ACTOR_EN_MA2", "EN_MA2", "EN_MA2"),
    ("ACTOR_EN_BOM_CHU", "EN_BOM_CHU", "EN_BOM_CHU"),
    ("ACTOR_EN_HORSE_GAME_CHECK", "EN_HORSE_GAME_CHECK", "EN_HORSE_GAME_CHECK"),
    ("ACTOR_BOSS_TW", "BOSS_TW", "BOSS_TW"),
    ("ACTOR_EN_RR", "EN_RR", "EN_RR"),
    ("ACTOR_EN_BA", "EN_BA", "EN_BA"),
    ("ACTOR_EN_BX", "EN_BX", "EN_BX"),
    ("ACTOR_EN_ANUBICE", "EN_ANUBICE", "EN_ANUBICE"),
    ("ACTOR_EN_ANUBICE_FIRE", "EN_ANUBICE_FIRE", "EN_ANUBICE_FIRE"),
    ("ACTOR_BG_MORI_HASHIGO", "BG_MORI_HASHIGO", "BG_MORI_HASHIGO"),
    ("ACTOR_BG_MORI_HASHIRA4", "BG_MORI_HASHIRA4", "BG_MORI_HASHIRA4"),
    ("ACTOR_BG_MORI_IDOMIZU", "BG_MORI_IDOMIZU", "BG_MORI_IDOMIZU"),
    ("ACTOR_BG_SPOT16_DOUGHNUT", "BG_SPOT16_DOUGHNUT", "BG_SPOT16_DOUGHNUT"),
    ("ACTOR_BG_BDAN_SWITCH", "BG_BDAN_SWITCH", "BG_BDAN_SWITCH"),
    ("ACTOR_EN_MA1", "EN_MA1", "EN_MA1"),
    ("ACTOR_BOSS_GANON", "BOSS_GANON", "BOSS_GANON"),
    ("ACTOR_BOSS_SST", "BOSS_SST", "BOSS_SST"),
    ("ACTOR_EN_NY", "EN_NY", "EN_NY"),
    ("ACTOR_EN_FR", "EN_FR", "EN_FR"),
    ("ACTOR_ITEM_SHIELD", "ITEM_SHIELD", "ITEM_SHIELD"),
    ("ACTOR_BG_ICE_SHELTER", "BG_ICE_SHELTER", "BG_ICE_SHELTER"),
    ("ACTOR_EN_ICE_HONO", "EN_ICE_HONO", "EN_ICE_HONO"),
    ("ACTOR_ITEM_OCARINA", "ITEM_OCARINA", "ITEM_OCARINA"),
    ("ACTOR_MAGIC_DARK", "MAGIC_DARK", "MAGIC_DARK"),
    ("ACTOR_DEMO_6K", "DEMO_6K", "DEMO_6K"),
    ("ACTOR_EN_ANUBICE_TAG", "EN_ANUBICE_TAG", "EN_ANUBICE_TAG"),
    ("ACTOR_BG_HAKA_GATE", "BG_HAKA_GATE", "BG_HAKA_GATE"),
    ("ACTOR_BG_SPOT15_SAKU", "BG_SPOT15_SAKU", "BG_SPOT15_SAKU"),
    ("ACTOR_BG_JYA_GOROIWA", "BG_JYA_GOROIWA", "BG_JYA_GOROIWA"),
    ("ACTOR_BG_JYA_ZURERUKABE", "BG_JYA_ZURERUKABE", "BG_JYA_ZURERUKABE"),
    ("ACTOR_BG_JYA_COBRA", "BG_JYA_COBRA", "BG_JYA_COBRA"),
    ("ACTOR_BG_JYA_KANAAMI", "BG_JYA_KANAAMI", "BG_JYA_KANAAMI"),
    ("ACTOR_FISHING", "FISHING", "FISHING"),
    ("ACTOR_OBJ_OSHIHIKI", "OBJ_OSHIHIKI", "OBJ_OSHIHIKI"),
    ("ACTOR_BG_GATE_SHUTTER", "BG_GATE_SHUTTER", "BG_GATE_SHUTTER"),
    ("ACTOR_EFF_DUST", "EFF_DUST", "EFF_DUST"),
    ("ACTOR_BG_SPOT01_FUSYA", "BG_SPOT01_FUSYA", "BG_SPOT01_FUSYA"),
    ("ACTOR_BG_SPOT01_IDOHASHIRA", "BG_SPOT01_IDOHASHIRA", "BG_SPOT01_IDOHASHIRA"),
    ("ACTOR_BG_SPOT01_IDOMIZU", "BG_SPOT01_IDOMIZU", "BG_SPOT01_IDOMIZU"),
    ("ACTOR_BG_PO_SYOKUDAI", "BG_PO_SYOKUDAI", "BG_PO_SYOKUDAI"),
    ("ACTOR_BG_GANON_OTYUKA", "BG_GANON_OTYUKA", "BG_GANON_OTYUKA"),
    ("ACTOR_BG_SPOT15_RRBOX", "BG_SPOT15_RRBOX", "BG_SPOT15_RRBOX"),
    ("ACTOR_BG_UMAJUMP", "BG_UMAJUMP", "BG_UMAJUMP"),
    ("ACTOR_ARROW_FIRE", "ARROW_FIRE", "ARROW_FIRE"),
    ("ACTOR_ARROW_ICE", "ARROW_ICE", "ARROW_ICE"),
    ("ACTOR_ARROW_LIGHT", "ARROW_LIGHT", "ARROW_LIGHT"),
    ("ACTOR_ITEM_ETCETERA", "ITEM_ETCETERA", "ITEM_ETCETERA"),
    ("ACTOR_OBJ_KIBAKO", "OBJ_KIBAKO", "OBJ_KIBAKO"),
    ("ACTOR_OBJ_TSUBO", "OBJ_TSUBO", "OBJ_TSUBO"),
    ("ACTOR_EN_WONDER_ITEM", "EN_WONDER_ITEM", "EN_WONDER_ITEM"),
    ("ACTOR_EN_IK", "EN_IK", "EN_IK"),
    ("ACTOR_DEMO_IK", "DEMO_IK", "DEMO_IK"),
    ("ACTOR_EN_SKJ", "EN_SKJ", "EN_SKJ"),
    ("ACTOR_EN_SKJNEEDLE", "EN_SKJNEEDLE", "EN_SKJNEEDLE"),
    ("ACTOR_EN_G_SWITCH", "EN_G_SWITCH", "EN_G_SWITCH"),
    ("ACTOR_DEMO_EXT", "DEMO_EXT", "DEMO_EXT"),
    ("ACTOR_DEMO_SHD", "DEMO_SHD", "DEMO_SHD"),
    ("ACTOR_EN_DNS", "EN_DNS", "EN_DNS"),
    ("ACTOR_ELF_MSG", "ELF_MSG", "ELF_MSG"),
    ("ACTOR_EN_HONOTRAP", "EN_HONOTRAP", "EN_HONOTRAP"),
    ("ACTOR_EN_TUBO_TRAP", "EN_TUBO_TRAP", "EN_TUBO_TRAP"),
    ("ACTOR_OBJ_ICE_POLY", "OBJ_ICE_POLY", "OBJ_ICE_POLY"),
    ("ACTOR_BG_SPOT03_TAKI", "BG_SPOT03_TAKI", "BG_SPOT03_TAKI"),
    ("ACTOR_BG_SPOT07_TAKI", "BG_SPOT07_TAKI", "BG_SPOT07_TAKI"),
    ("ACTOR_EN_FZ", "EN_FZ", "EN_FZ"),
    ("ACTOR_EN_PO_RELAY", "EN_PO_RELAY", "EN_PO_RELAY"),
    ("ACTOR_BG_RELAY_OBJECTS", "BG_RELAY_OBJECTS", "BG_RELAY_OBJECTS"),
    ("ACTOR_EN_DIVING_GAME", "EN_DIVING_GAME", "EN_DIVING_GAME"),
    ("ACTOR_EN_KUSA", "EN_KUSA", "EN_KUSA"),
    ("ACTOR_OBJ_BEAN", "OBJ_BEAN", "OBJ_BEAN"),
    ("ACTOR_OBJ_BOMBIWA", "OBJ_BOMBIWA", "OBJ_BOMBIWA"),
    ("ACTOR_OBJ_SWITCH", "OBJ_SWITCH", "OBJ_SWITCH"),
    ("ACTOR_OBJ_ELEVATOR", "OBJ_ELEVATOR", "OBJ_ELEVATOR"),
    ("ACTOR_OBJ_LIFT", "OBJ_LIFT", "OBJ_LIFT"),
    ("ACTOR_OBJ_HSBLOCK", "OBJ_HSBLOCK", "OBJ_HSBLOCK"),
    ("ACTOR_EN_OKARINA_TAG", "EN_OKARINA_TAG", "EN_OKARINA_TAG"),
    ("ACTOR_EN_YABUSAME_MARK", "EN_YABUSAME_MARK", "EN_YABUSAME_MARK"),
    ("ACTOR_EN_GOROIWA", "EN_GOROIWA", "EN_GOROIWA"),
    ("ACTOR_EN_EX_RUPPY", "EN_EX_RUPPY", "EN_EX_RUPPY"),
    ("ACTOR_EN_TORYO", "EN_TORYO", "EN_TORYO"),
    ("ACTOR_EN_DAIKU", "EN_DAIKU", "EN_DAIKU"),
    ("ACTOR_EN_NWC", "EN_NWC", "EN_NWC"),
    ("ACTOR_EN_BLKOBJ", "EN_BLKOBJ", "EN_BLKOBJ"),
    ("ACTOR_ITEM_INBOX", "ITEM_INBOX", "ITEM_INBOX"),
    ("ACTOR_EN_GE1", "EN_GE1", "EN_GE1"),
    ("ACTOR_OBJ_BLOCKSTOP", "OBJ_BLOCKSTOP", "OBJ_BLOCKSTOP"),
    ("ACTOR_EN_SDA", "EN_SDA", "EN_SDA"),
    ("ACTOR_EN_CLEAR_TAG", "EN_CLEAR_TAG", "EN_CLEAR_TAG"),
    ("ACTOR_EN_NIW_LADY", "EN_NIW_LADY", "EN_NIW_LADY"),
    ("ACTOR_EN_GM", "EN_GM", "EN_GM"),
    ("ACTOR_EN_MS", "EN_MS", "EN_MS"),
    ("ACTOR_EN_HS", "EN_HS", "EN_HS"),
    ("ACTOR_BG_INGATE", "BG_INGATE", "BG_INGATE"),
    ("ACTOR_EN_KANBAN", "EN_KANBAN", "EN_KANBAN"),
    ("ACTOR_EN_HEISHI3", "EN_HEISHI3", "EN_HEISHI3"),
    ("ACTOR_EN_SYATEKI_NIW", "EN_SYATEKI_NIW", "EN_SYATEKI_NIW"),
    ("ACTOR_EN_ATTACK_NIW", "EN_ATTACK_NIW", "EN_ATTACK_NIW"),
    ("ACTOR_BG_SPOT01_IDOSOKO", "BG_SPOT01_IDOSOKO", "BG_SPOT01_IDOSOKO"),
    ("ACTOR_EN_SA", "EN_SA", "EN_SA"),
    ("ACTOR_EN_WONDER_TALK", "EN_WONDER_TALK", "EN_WONDER_TALK"),
    ("ACTOR_BG_GJYO_BRIDGE", "BG_GJYO_BRIDGE", "BG_GJYO_BRIDGE"),
    ("ACTOR_EN_DS", "EN_DS", "EN_DS"),
    ("ACTOR_EN_MK", "EN_MK", "EN_MK"),
    ("ACTOR_EN_BOM_BOWL_MAN", "EN_BOM_BOWL_MAN", "EN_BOM_BOWL_MAN"),
    ("ACTOR_EN_BOM_BOWL_PIT", "EN_BOM_BOWL_PIT", "EN_BOM_BOWL_PIT"),
    ("ACTOR_EN_OWL", "EN_OWL", "EN_OWL"),
    ("ACTOR_EN_ISHI", "EN_ISHI", "EN_ISHI"),
    ("ACTOR_OBJ_HANA", "OBJ_HANA", "OBJ_HANA"),
    ("ACTOR_OBJ_LIGHTSWITCH", "OBJ_LIGHTSWITCH", "OBJ_LIGHTSWITCH"),
    ("ACTOR_OBJ_MURE2", "OBJ_MURE2", "OBJ_MURE2"),
    ("ACTOR_EN_GO", "EN_GO", "EN_GO"),
    ("ACTOR_EN_FU", "EN_FU", "EN_FU"),
    ("ACTOR_EN_CHANGER", "EN_CHANGER", "EN_CHANGER"),
    ("ACTOR_BG_JYA_MEGAMI", "BG_JYA_MEGAMI", "BG_JYA_MEGAMI"),
    ("ACTOR_BG_JYA_LIFT", "BG_JYA_LIFT", "BG_JYA_LIFT"),
    ("ACTOR_BG_JYA_BIGMIRROR", "BG_JYA_BIGMIRROR", "BG_JYA_BIGMIRROR"),
    ("ACTOR_BG_JYA_BOMBCHUIWA", "BG_JYA_BOMBCHUIWA", "BG_JYA_BOMBCHUIWA"),
    ("ACTOR_BG_JYA_AMISHUTTER", "BG_JYA_AMISHUTTER", "BG_JYA_AMISHUTTER"),
    ("ACTOR_BG_JYA_BOMBIWA", "BG_JYA_BOMBIWA", "BG_JYA_BOMBIWA"),
    ("ACTOR_BG_SPOT18_BASKET", "BG_SPOT18_BASKET", "BG_SPOT18_BASKET"),
    ("ACTOR_EN_GANON_ORGAN", "EN_GANON_ORGAN", "EN_GANON_ORGAN"),
    ("ACTOR_EN_SIOFUKI", "EN_SIOFUKI", "EN_SIOFUKI"),
    ("ACTOR_EN_STREAM", "EN_STREAM", "EN_STREAM"),
    ("ACTOR_EN_MM", "EN_MM", "EN_MM"),
    ("ACTOR_EN_KO", "EN_KO", "EN_KO"),
    ("ACTOR_EN_KZ", "EN_KZ", "EN_KZ"),
    ("ACTOR_EN_WEATHER_TAG", "EN_WEATHER_TAG", "EN_WEATHER_TAG"),
    ("ACTOR_BG_SST_FLOOR", "BG_SST_FLOOR", "BG_SST_FLOOR"),
    ("ACTOR_EN_ANI", "EN_ANI", "EN_ANI"),
    ("ACTOR_EN_EX_ITEM", "EN_EX_ITEM", "EN_EX_ITEM"),
    ("ACTOR_BG_JYA_IRONOBJ", "BG_JYA_IRONOBJ", "BG_JYA_IRONOBJ"),
    ("ACTOR_EN_JS", "EN_JS", "EN_JS"),
    ("ACTOR_EN_JSJUTAN", "EN_JSJUTAN", "EN_JSJUTAN"),
    ("ACTOR_EN_CS", "EN_CS", "EN_CS"),
    ("ACTOR_EN_MD", "EN_MD", "EN_MD"),
    ("ACTOR_EN_HY", "EN_HY", "EN_HY"),
    ("ACTOR_EN_GANON_MANT", "EN_GANON_MANT", "EN_GANON_MANT"),
    ("ACTOR_EN_OKARINA_EFFECT", "EN_OKARINA_EFFECT", "EN_OKARINA_EFFECT"),
    ("ACTOR_EN_MAG", "EN_MAG", "EN_MAG"),
    ("ACTOR_DOOR_GERUDO", "DOOR_GERUDO", "DOOR_GERUDO"),
    ("ACTOR_ELF_MSG2", "ELF_MSG2", "ELF_MSG2"),
    ("ACTOR_DEMO_GT", "DEMO_GT", "DEMO_GT"),
    ("ACTOR_EN_PO_FIELD", "EN_PO_FIELD", "EN_PO_FIELD"),
    ("ACTOR_EFC_ERUPC", "EFC_ERUPC", "EFC_ERUPC"),
    ("ACTOR_BG_ZG", "BG_ZG", "BG_ZG"),
    ("ACTOR_EN_HEISHI4", "EN_HEISHI4", "EN_HEISHI4"),
    ("ACTOR_EN_ZL3", "EN_ZL3", "EN_ZL3"),
    ("ACTOR_BOSS_GANON2", "BOSS_GANON2", "BOSS_GANON2"),
    ("ACTOR_EN_KAKASI", "EN_KAKASI", "EN_KAKASI"),
    ("ACTOR_EN_TAKARA_MAN", "EN_TAKARA_MAN", "EN_TAKARA_MAN"),
    ("ACTOR_OBJ_MAKEOSHIHIKI", "OBJ_MAKEOSHIHIKI", "OBJ_MAKEOSHIHIKI"),
    ("ACTOR_OCEFF_SPOT", "OCEFF_SPOT", "OCEFF_SPOT"),
    ("ACTOR_END_TITLE", "END_TITLE", "END_TITLE"),
    ("ACTOR_EN_TORCH", "EN_TORCH", "EN_TORCH"),
    ("ACTOR_DEMO_EC", "DEMO_EC", "DEMO_EC"),
    ("ACTOR_SHOT_SUN", "SHOT_SUN", "SHOT_SUN"),
    ("ACTOR_EN_DY_EXTRA", "EN_DY_EXTRA", "EN_DY_EXTRA"),
    ("ACTOR_EN_WONDER_TALK2", "EN_WONDER_TALK2", "EN_WONDER_TALK2"),
    ("ACTOR_EN_GE2", "EN_GE2", "EN_GE2"),
    ("ACTOR_OBJ_ROOMTIMER", "OBJ_ROOMTIMER", "OBJ_ROOMTIMER"),
    ("ACTOR_EN_SSH", "EN_SSH", "EN_SSH"),
    ("ACTOR_EN_STH", "EN_STH", "EN_STH"),
    ("ACTOR_OCEFF_WIPE", "OCEFF_WIPE", "OCEFF_WIPE"),
    ("ACTOR_OCEFF_STORM", "OCEFF_STORM", "OCEFF_STORM"),
    ("ACTOR_EN_WEIYER", "EN_WEIYER", "EN_WEIYER"),
    ("ACTOR_BG_SPOT05_SOKO", "BG_SPOT05_SOKO", "BG_SPOT05_SOKO"),
    ("ACTOR_BG_JYA_1FLIFT", "BG_JYA_1FLIFT", "BG_JYA_1FLIFT"),
    ("ACTOR_BG_JYA_HAHENIRON", "BG_JYA_HAHENIRON", "BG_JYA_HAHENIRON"),
    ("ACTOR_BG_SPOT12_GATE", "BG_SPOT12_GATE", "BG_SPOT12_GATE"),
    ("ACTOR_BG_SPOT12_SAKU", "BG_SPOT12_SAKU", "BG_SPOT12_SAKU"),
    ("ACTOR_EN_HINTNUTS", "EN_HINTNUTS", "EN_HINTNUTS"),
    ("ACTOR_EN_NUTSBALL", "EN_NUTSBALL", "EN_NUTSBALL"),
    ("ACTOR_BG_SPOT00_BREAK", "BG_SPOT00_BREAK", "BG_SPOT00_BREAK"),
    ("ACTOR_EN_SHOPNUTS", "EN_SHOPNUTS", "EN_SHOPNUTS"),
    ("ACTOR_EN_IT", "EN_IT", "EN_IT"),
    ("ACTOR_EN_GELDB", "EN_GELDB", "EN_GELDB"),
    ("ACTOR_OCEFF_WIPE2", "OCEFF_WIPE2", "OCEFF_WIPE2"),
    ("ACTOR_OCEFF_WIPE3", "OCEFF_WIPE3", "OCEFF_WIPE3"),
    ("ACTOR_EN_NIW_GIRL", "EN_NIW_GIRL", "EN_NIW_GIRL"),
    ("ACTOR_EN_DOG", "EN_DOG", "EN_DOG"),
    ("ACTOR_EN_SI", "EN_SI", "EN_SI"),
    ("ACTOR_BG_SPOT01_OBJECTS2", "BG_SPOT01_OBJECTS2", "BG_SPOT01_OBJECTS2"),
    ("ACTOR_OBJ_COMB", "OBJ_COMB", "OBJ_COMB"),
    ("ACTOR_BG_SPOT11_BAKUDANKABE", "BG_SPOT11_BAKUDANKABE", "BG_SPOT11_BAKUDANKABE"),
    ("ACTOR_OBJ_KIBAKO2", "OBJ_KIBAKO2", "OBJ_KIBAKO2"),
    ("ACTOR_EN_DNT_DEMO", "EN_DNT_DEMO", "EN_DNT_DEMO"),
    ("ACTOR_EN_DNT_JIJI", "EN_DNT_JIJI", "EN_DNT_JIJI"),
    ("ACTOR_EN_DNT_NOMAL", "EN_DNT_NOMAL", "EN_DNT_NOMAL"),
    ("ACTOR_EN_GUEST", "EN_GUEST", "EN_GUEST"),
    ("ACTOR_BG_BOM_GUARD", "BG_BOM_GUARD", "BG_BOM_GUARD"),
    ("ACTOR_EN_HS2", "EN_HS2", "EN_HS2"),
    ("ACTOR_DEMO_KEKKAI", "DEMO_KEKKAI", "DEMO_KEKKAI"),
    ("ACTOR_BG_SPOT08_BAKUDANKABE", "BG_SPOT08_BAKUDANKABE", "BG_SPOT08_BAKUDANKABE"),
    ("ACTOR_BG_SPOT17_BAKUDANKABE", "BG_SPOT17_BAKUDANKABE", "BG_SPOT17_BAKUDANKABE"),
    ("ACTOR_OBJ_MURE3", "OBJ_MURE3", "OBJ_MURE3"),
    ("ACTOR_EN_TG", "EN_TG", "EN_TG"),
    ("ACTOR_EN_MU", "EN_MU", "EN_MU"),
    ("ACTOR_EN_GO2", "EN_GO2", "EN_GO2"),
    ("ACTOR_EN_WF", "EN_WF", "EN_WF"),
    ("ACTOR_EN_SKB", "EN_SKB", "EN_SKB"),
    ("ACTOR_DEMO_GJ", "DEMO_GJ", "DEMO_GJ"),
    ("ACTOR_DEMO_GEFF", "DEMO_GEFF", "DEMO_GEFF"),
    ("ACTOR_BG_GND_FIREMEIRO", "BG_GND_FIREMEIRO", "BG_GND_FIREMEIRO"),
    ("ACTOR_BG_GND_DARKMEIRO", "BG_GND_DARKMEIRO", "BG_GND_DARKMEIRO"),
    ("ACTOR_BG_GND_SOULMEIRO", "BG_GND_SOULMEIRO", "BG_GND_SOULMEIRO"),
    ("ACTOR_BG_GND_NISEKABE", "BG_GND_NISEKABE", "BG_GND_NISEKABE"),
    ("ACTOR_BG_GND_ICEBLOCK", "BG_GND_ICEBLOCK", "BG_GND_ICEBLOCK"),
    ("ACTOR_EN_GB", "EN_GB", "EN_GB"),
    ("ACTOR_EN_GS", "EN_GS", "EN_GS"),
    ("ACTOR_BG_MIZU_BWALL", "BG_MIZU_BWALL", "BG_MIZU_BWALL"),
    ("ACTOR_BG_MIZU_SHUTTER", "BG_MIZU_SHUTTER", "BG_MIZU_SHUTTER"),
    ("ACTOR_EN_DAIKU_KAKARIKO", "EN_DAIKU_KAKARIKO", "EN_DAIKU_KAKARIKO"),
    ("ACTOR_BG_BOWL_WALL", "BG_BOWL_WALL", "BG_BOWL_WALL"),
    ("ACTOR_EN_WALL_TUBO", "EN_WALL_TUBO", "EN_WALL_TUBO"),
    ("ACTOR_EN_PO_DESERT", "EN_PO_DESERT", "EN_PO_DESERT"),
    ("ACTOR_EN_CROW", "EN_CROW", "EN_CROW"),
    ("ACTOR_DOOR_KILLER", "DOOR_KILLER", "DOOR_KILLER"),
    ("ACTOR_BG_SPOT11_OASIS", "BG_SPOT11_OASIS", "BG_SPOT11_OASIS"),
    ("ACTOR_BG_SPOT18_FUTA", "BG_SPOT18_FUTA", "BG_SPOT18_FUTA"),
    ("ACTOR_BG_SPOT18_SHUTTER", "BG_SPOT18_SHUTTER", "BG_SPOT18_SHUTTER"),
    ("ACTOR_EN_MA3", "EN_MA3", "EN_MA3"),
    ("ACTOR_EN_COW", "EN_COW", "EN_COW"),
    ("ACTOR_BG_ICE_TURARA", "BG_ICE_TURARA", "BG_ICE_TURARA"),
    ("ACTOR_BG_ICE_SHUTTER", "BG_ICE_SHUTTER", "BG_ICE_SHUTTER"),
    ("ACTOR_EN_KAKASI2", "EN_KAKASI2", "EN_KAKASI2"),
    ("ACTOR_EN_KAKASI3", "EN_KAKASI3", "EN_KAKASI3"),
    ("ACTOR_OCEFF_WIPE4", "OCEFF_WIPE4", "OCEFF_WIPE4"),
    ("ACTOR_EN_EG", "EN_EG", "EN_EG"),
    ("ACTOR_BG_MENKURI_NISEKABE", "BG_MENKURI_NISEKABE", "BG_MENKURI_NISEKABE"),
    ("ACTOR_EN_ZO", "EN_ZO", "EN_ZO"),
    ("ACTOR_OBJ_MAKEKINSUTA", "OBJ_MAKEKINSUTA", "OBJ_MAKEKINSUTA"),
    ("ACTOR_EN_GE3", "EN_GE3", "EN_GE3"),
    ("ACTOR_OBJ_TIMEBLOCK", "OBJ_TIMEBLOCK", "OBJ_TIMEBLOCK"),
    ("ACTOR_OBJ_HAMISHI", "OBJ_HAMISHI", "OBJ_HAMISHI"),
    ("ACTOR_EN_ZL4", "EN_ZL4", "EN_ZL4"),
    ("ACTOR_EN_MM2", "EN_MM2", "EN_MM2"),
    ("ACTOR_BG_JYA_BLOCK", "BG_JYA_BLOCK", "BG_JYA_BLOCK"),
    ("ACTOR_OBJ_WARP2BLOCK", "OBJ_WARP2BLOCK", "OBJ_WARP2BLOCK"),
]

ootEnumLinkIdle = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "Default", "Default"),
    ("0x01", "Sneezing", "Sneezing"),
    ("0x02", "Wiping Forehead", "Wiping Forehead"),
    ("0x03", "Too Hot", "Too Hot (Triggers Heat Timer)"),
    ("0x04", "Yawning", "Yawning"),
    ("0x07", "Gasping For Breath", "Gasping For Breath"),
    ("0x09", "Brandish Sword", "Brandish Sword"),
    ("0x0A", "Adjust Tunic", "Adjust Tunic"),
    ("0xFF", "Hops On Epona", "Hops On Epona"),
]

# Make sure to add exceptions in utility.py - selectMeshChildrenOnly
ootEnumEmptyType = [
    ("None", "None", "None"),
    ("Scene", "Scene", "Scene"),
    ("Room", "Room", "Room"),
    ("Actor", "Actor", "Actor"),
    ("Transition Actor", "Transition Actor", "Transition Actor"),
    ("Entrance", "Entrance", "Entrance"),
    ("Water Box", "Water Box", "Water Box"),
    ("Cull Group", "Cull Group", "Cull Group"),
    ("LOD", "LOD Group", "LOD Group"),
    ("Cutscene", "Cutscene", "Cutscene"),
    # ('Camera Volume', 'Camera Volume', 'Camera Volume'),
]

ootEnumCloudiness = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "Sunny", "Sunny"),
    ("0x01", "Cloudy", "Cloudy"),
]

ootEnumCameraMode = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "Default", "Default"),
    ("0x10", "Two Views, No C-Up", "Two Views, No C-Up"),
    ("0x20", "Rotating Background, Bird's Eye C-Up", "Rotating Background, Bird's Eye C-Up"),
    ("0x30", "Fixed Background, No C-Up", "Fixed Background, No C-Up"),
    ("0x40", "Rotating Background, No C-Up", "Rotating Background, No C-Up"),
    ("0x50", "Shooting Gallery", "Shooting Gallery"),
]

ootEnumMapLocation = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "Hyrule Field", "Hyrule Field"),
    ("0x01", "Kakariko Village", "Kakariko Village"),
    ("0x02", "Graveyard", "Graveyard"),
    ("0x03", "Zora's River", "Zora's River"),
    ("0x04", "Kokiri Forest", "Kokiri Forest"),
    ("0x05", "Sacred Forest Meadow", "Sacred Forest Meadow"),
    ("0x06", "Lake Hylia", "Lake Hylia"),
    ("0x07", "Zora's Domain", "Zora's Domain"),
    ("0x08", "Zora's Fountain", "Zora's Fountain"),
    ("0x09", "Gerudo Valley", "Gerudo Valley"),
    ("0x0A", "Lost Woods", "Lost Woods"),
    ("0x0B", "Desert Colossus", "Desert Colossus"),
    ("0x0C", "Gerudo's Fortress", "Gerudo's Fortress"),
    ("0x0D", "Haunted Wasteland", "Haunted Wasteland"),
    ("0x0E", "Market", "Market"),
    ("0x0F", "Hyrule Castle", "Hyrule Castle"),
    ("0x10", "Death Mountain Trail", "Death Mountain Trail"),
    ("0x11", "Death Mountain Crater", "Death Mountain Crater"),
    ("0x12", "Goron City", "Goron City"),
    ("0x13", "Lon Lon Ranch", "Lon Lon Ranch"),
    ("0x14", "Dampe's Grave & Windmill", "Dampe's Grave & Windmill"),
    ("0x15", "Ganon's Castle", "Ganon's Castle"),
    ("0x16", "Grottos & Fairy Fountains", "Grottos & Fairy Fountains"),
]

ootEnumSkybox = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "None", "None"),
    ("0x01", "Standard Sky", "Standard Sky"),
    ("0x02", "Hylian Bazaar", "Hylian Bazaar"),
    ("0x03", "Brown Cloudy Sky", "Brown Cloudy Sky"),
    ("0x04", "Market Ruins", "Market Ruins"),
    ("0x05", "Black Cloudy Night", "Black Cloudy Night"),
    ("0x07", "Link's House", "Link's House"),
    ("0x09", "Market (Main Square, Day)", "Market (Main Square, Day)"),
    ("0x0A", "Market (Main Square, Night)", "Market (Main Square, Night)"),
    ("0x0B", "Happy Mask Shop", "Happy Mask Shop"),
    ("0x0C", "Know-It-All Brothers' House", "Know-It-All Brothers' House"),
    ("0x0E", "Kokiri Twins' House", "Kokiri Twins' House"),
    ("0x0F", "Stable", "Stable"),
    ("0x10", "Stew Lady's House", "Stew Lady's House"),
    ("0x11", "Kokiri Shop", "Kokiri Shop"),
    ("0x13", "Goron Shop", "Goron Shop"),
    ("0x14", "Zora Shop", "Zora Shop"),
    ("0x16", "Kakariko Potions Shop", "Kakariko Potions Shop"),
    ("0x17", "Hylian Potions Shop", "Hylian Potions Shop"),
    ("0x18", "Bomb Shop", "Bomb Shop"),
    ("0x1A", "Dog Lady's House", "Dog Lady's House"),
    ("0x1B", "Impa's House", "Impa's House"),
    ("0x1C", "Gerudo Tent", "Gerudo Tent"),
    ("0x1D", "Environment Color", "Environment Color"),
    ("0x20", "Mido's House", "Mido's House"),
    ("0x21", "Saria's House", "Saria's House"),
    ("0x22", "Dog Guy's House", "Dog Guy's House"),
]

ootEnumSkyboxLighting = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "Time Of Day", "Time Of Day"),
    ("0x01", "Indoor", "Indoor"),
]

ootEnumAudioSessionPreset = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "0x00", "0x00"),
]

ootEnumMusicSeq = [
    ("Custom", "Custom", "Custom"),
    ("0x02", "Hyrule Field", "Hyrule Field"),
    ("0x03", "Hyrule Field (Initial Segment From Loading Area)", "Hyrule Field (Initial Segment From Loading Area)"),
    ("0x04", "Hyrule Field (Moving Segment 1)", "Hyrule Field (Moving Segment 1)"),
    ("0x05", "Hyrule Field (Moving Segment 2)", "Hyrule Field (Moving Segment 2)"),
    ("0x06", "Hyrule Field (Moving Segment 3)", "Hyrule Field (Moving Segment 3)"),
    ("0x07", "Hyrule Field (Moving Segment 4)", "Hyrule Field (Moving Segment 4)"),
    ("0x08", "Hyrule Field (Moving Segment 5)", "Hyrule Field (Moving Segment 5)"),
    ("0x09", "Hyrule Field (Moving Segment 6)", "Hyrule Field (Moving Segment 6)"),
    ("0x0A", "Hyrule Field (Moving Segment 7)", "Hyrule Field (Moving Segment 7)"),
    ("0x0B", "Hyrule Field (Moving Segment 8)", "Hyrule Field (Moving Segment 8)"),
    ("0x0C", "Hyrule Field (Moving Segment 9)", "Hyrule Field (Moving Segment 9)"),
    ("0x0D", "Hyrule Field (Moving Segment 10)", "Hyrule Field (Moving Segment 10)"),
    ("0x0E", "Hyrule Field (Moving Segment 11)", "Hyrule Field (Moving Segment 11)"),
    ("0x0F", "Hyrule Field (Enemy Approaches)", "Hyrule Field (Enemy Approaches)"),
    ("0x10", "Hyrule Field (Enemy Near Segment 1)", "Hyrule Field (Enemy Near Segment 1)"),
    ("0x11", "Hyrule Field (Enemy Near Segment 2)", "Hyrule Field (Enemy Near Segment 2)"),
    ("0x12", "Hyrule Field (Enemy Near Segment 3)", "Hyrule Field (Enemy Near Segment 3)"),
    ("0x13", "Hyrule Field (Enemy Near Segment 4)", "Hyrule Field (Enemy Near Segment 4)"),
    ("0x14", "Hyrule Field (Standing Still Segment 1)", "Hyrule Field (Standing Still Segment 1)"),
    ("0x15", "Hyrule Field (Standing Still Segment 2)", "Hyrule Field (Standing Still Segment 2)"),
    ("0x16", "Hyrule Field (Standing Still Segment 3)", "Hyrule Field (Standing Still Segment 3)"),
    ("0x17", "Hyrule Field (Standing Still Segment 4)", "Hyrule Field (Standing Still Segment 4)"),
    ("0x18", "Dodongo's Cavern", "Dodongo's Cavern"),
    ("0x19", "Kakariko Village (Adult)", "Kakariko Village (Adult)"),
    ("0x1A", "Enemy Battle", "Enemy Battle"),
    ("0x1B", "Boss Battle 00", "Boss Battle 00"),
    ("0x1C", "Inside the Deku Tree", "Inside the Deku Tree"),
    ("0x1D", "Market", "Market"),
    ("0x1E", "Title Theme", "Title Theme"),
    ("0x1F", "Link's House", "Link's House"),
    ("0x20", "Game Over", "Game Over"),
    ("0x21", "Boss Clear", "Boss Clear"),
    ("0x22", "Item Get", "Item Get"),
    ("0x23", "Opening Ganon", "Opening Ganon"),
    ("0x24", "Heart Get", "Heart Get"),
    ("0x25", "Prelude Of Light", "Prelude Of Light"),
    ("0x26", "Inside Jabu-Jabu's Belly", "Inside Jabu-Jabu's Belly"),
    ("0x27", "Kakariko Village (Child)", "Kakariko Village (Child)"),
    ("0x28", "Great Fairy's Fountain", "Great Fairy's Fountain"),
    ("0x29", "Zelda's Theme", "Zelda's Theme"),
    ("0x2A", "Fire Temple", "Fire Temple"),
    ("0x2B", "Open Treasure Chest", "Open Treasure Chest"),
    ("0x2C", "Forest Temple", "Forest Temple"),
    ("0x2D", "Hyrule Castle Courtyard", "Hyrule Castle Courtyard"),
    ("0x2E", "Ganondorf's Theme", "Ganondorf's Theme"),
    ("0x2F", "Lon Lon Ranch", "Lon Lon Ranch"),
    ("0x30", "Goron City", "Goron City "),
    ("0x31", "Hyrule Field Morning Theme", "Hyrule Field Morning Theme"),
    ("0x32", "Spiritual Stone Get", "Spiritual Stone Get"),
    ("0x33", "Bolero of Fire", "Bolero of Fire"),
    ("0x34", "Minuet of Woods", "Minuet of Woods"),
    ("0x35", "Serenade of Water", "Serenade of Water"),
    ("0x36", "Requiem of Spirit", "Requiem of Spirit"),
    ("0x37", "Nocturne of Shadow", "Nocturne of Shadow"),
    ("0x38", "Mini-Boss Battle", "Mini-Boss Battle"),
    ("0x39", "Obtain Small Item", "Obtain Small Item"),
    ("0x3A", "Temple of Time", "Temple of Time"),
    ("0x3B", "Escape from Lon Lon Ranch", "Escape from Lon Lon Ranch"),
    ("0x3C", "Kokiri Forest", "Kokiri Forest"),
    ("0x3D", "Obtain Fairy Ocarina", "Obtain Fairy Ocarina"),
    ("0x3E", "Lost Woods", "Lost Woods"),
    ("0x3F", "Spirit Temple", "Spirit Temple"),
    ("0x40", "Horse Race", "Horse Race"),
    ("0x41", "Horse Race Goal", "Horse Race Goal"),
    ("0x42", "Ingo's Theme", "Ingo's Theme"),
    ("0x43", "Obtain Medallion", "Obtain Medallion"),
    ("0x44", "Ocarina Saria's Song", "Ocarina Saria's Song"),
    ("0x45", "Ocarina Epona's Song", "Ocarina Epona's Song"),
    ("0x46", "Ocarina Zelda's Lullaby", "Ocarina Zelda's Lullaby"),
    ("0x47", "Sun's Song", "Sun's Song"),
    ("0x48", "Song of Time", "Song of Time"),
    ("0x49", "Song of Storms", "Song of Storms"),
    ("0x4A", "Fairy Flying", "Fairy Flying"),
    ("0x4B", "Deku Tree", "Deku Tree"),
    ("0x4C", "Windmill Hut", "Windmill Hut"),
    ("0x4D", "Legend of Hyrule", "Legend of Hyrule"),
    ("0x4E", "Shooting Gallery", "Shooting Gallery"),
    ("0x4F", "Sheik's Theme", "Sheik's Theme"),
    ("0x50", "Zora's Domain", "Zora's Domain"),
    ("0x51", "Enter Zelda", "Enter Zelda"),
    ("0x52", "Goodbye to Zelda", "Goodbye to Zelda"),
    ("0x53", "Master Sword", "Master Sword"),
    ("0x54", "Ganon Intro", "Ganon Intro"),
    ("0x55", "Shop", "Shop"),
    ("0x56", "Chamber of the Sages", "Chamber of the Sages"),
    ("0x57", "File Select", "File Select"),
    ("0x58", "Ice Cavern", "Ice Cavern"),
    ("0x59", "Open Door of Temple of Time", "Open Door of Temple of Time"),
    ("0x5A", "Kaepora Gaebora's Theme", "Kaepora Gaebora's Theme"),
    ("0x5B", "Shadow Temple", "Shadow Temple"),
    ("0x5C", "Water Temple", "Water Temple"),
    ("0x5D", "Ganon's Castle Bridge", "Ganon's Castle Bridge"),
    ("0x5E", "Ocarina of Time", "Ocarina of Time"),
    ("0x5F", "Gerudo Valley", "Gerudo Valley"),
    ("0x60", "Potion Shop", "Potion Shop"),
    ("0x61", "Kotake & Koume's Theme", "Kotake & Koume's Theme"),
    ("0x62", "Escape from Ganon's Castle", "Escape from Ganon's Castle"),
    ("0x63", "Ganon's Castle Under Ground", "Ganon's Castle Under Ground"),
    ("0x64", "Ganondorf Battle", "Ganondorf Battle"),
    ("0x65", "Ganon Battle", "Ganon Battle"),
    ("0x66", "Seal of Six Sages", "Seal of Six Sages"),
    ("0x67", "End Credits I", "End Credits I"),
    ("0x68", "End Credits II", "End Credits II"),
    ("0x69", "End Credits III", "End Credits III"),
    ("0x6A", "End Credits IV", "End Credits IV"),
    ("0x6B", "King Dodongo & Volvagia Boss Battle", "King Dodongo & Volvagia Boss Battle"),
    ("0x6C", "Mini-Game", "Mini-Game"),
]

ootEnumNightSeq = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "Standard night [day and night cycle]", "0x00"),
    ("0x01", "Standard night [Kakariko]", "0x01"),
    ("0x02", "Distant storm [Graveyard]", "0x02"),
    ("0x03", "Howling wind and cawing [Ganon's Castle]", "0x03"),
    ("0x04", "Wind + night birds [Kokiri]", "0x04"),
    ("0x05", "Wind + crickets", "0x05"),
    ("0x06", "Wind", "0x06"),
    ("0x07", "Howling wind", "0x07"),
    ("0x08", "Wind + crickets", "0x08"),
    ("0x09", "Wind + crickets", "0x09"),
    ("0x0A", "Tubed howling wind [Wasteland]", "0x0A"),
    ("0x0B", "Tubed howling wind [Colossus]", "0x0B"),
    ("0x0C", "Wind", "0x0C"),
    ("0x0D", "Wind + crickets", "0x0D"),
    ("0x0E", "Wind + crickets", "0x0E"),
    ("0x0F", "Wind + birds", "0x0F"),
    ("0x10", "Wind + crickets", "0x10"),
    ("0x11", "?", "0x11"),
    ("0x12", "Wind + crickets", "0x12"),
    ("0x13", "Day music always playing", "0x13"),
    ("0x14", "Silence", "0x14"),
    ("0x16", "Silence", "0x16"),
    ("0x17", "High tubed wind + rain", "0x17"),
    ("0x18", "Silence", "0x18"),
    ("0x19", "Silence", "0x19"),
    ("0x1A", "High tubed wind + rain", "0x1A"),
    ("0x1B", "Silence", "0x1B"),
    ("0x1C", "Rain", "0x1C"),
    ("0x1D", "High tubed wind + rain", "0x1D"),
    ("0x1E", "Silence", "0x1E"),
    ("0x1F", "High tubed wind + rain ", "0x1F"),
]

ootEnumObjectID = [
    ("Custom", "Custom", "Custom"),
    ("OBJECT_HUMAN", "Human", "Human"),
    ("OBJECT_OKUTA", "Okuta", "Okuta"),
    ("OBJECT_CROW", "Crow", "Crow"),
    ("OBJECT_POH", "Poh", "Poh"),
    ("OBJECT_DY_OBJ", "Dy Obj", "Dy Obj"),
    ("OBJECT_WALLMASTER", "Wallmaster", "Wallmaster"),
    ("OBJECT_DODONGO", "Dodongo", "Dodongo"),
    ("OBJECT_FIREFLY", "Firefly", "Firefly"),
    ("OBJECT_BOX", "Box", "Box"),
    ("OBJECT_FIRE", "Fire", "Fire"),
    ("OBJECT_BUBBLE", "Bubble", "Bubble"),
    ("OBJECT_NIW", "Niw", "Niw"),
    ("OBJECT_TITE", "Tite", "Tite"),
    ("OBJECT_REEBA", "Reeba", "Reeba"),
    ("OBJECT_PEEHAT", "Peehat", "Peehat"),
    ("OBJECT_KINGDODONGO", "Kingdodongo", "Kingdodongo"),
    ("OBJECT_HORSE", "Horse", "Horse"),
    ("OBJECT_ZF", "Zf", "Zf"),
    ("OBJECT_GOMA", "Goma", "Goma"),
    ("OBJECT_ZL1", "Zl1", "Zl1"),
    ("OBJECT_GOL", "Gol", "Gol"),
    ("OBJECT_DODOJR", "Dodojr", "Dodojr"),
    ("OBJECT_TORCH2", "Torch2", "Torch2"),
    ("OBJECT_BL", "Bl", "Bl"),
    ("OBJECT_TP", "Tp", "Tp"),
    ("OBJECT_OA1", "Oa1", "Oa1"),
    ("OBJECT_ST", "St", "St"),
    ("OBJECT_BW", "Bw", "Bw"),
    ("OBJECT_EI", "Ei", "Ei"),
    ("OBJECT_HORSE_NORMAL", "Horse Normal", "Horse Normal"),
    ("OBJECT_OB1", "Ob1", "Ob1"),
    ("OBJECT_O_ANIME", "O Anime", "O Anime"),
    ("OBJECT_SPOT04_OBJECTS", "Spot04 Objects", "Spot04 Objects"),
    ("OBJECT_DDAN_OBJECTS", "Ddan Objects", "Ddan Objects"),
    ("OBJECT_HIDAN_OBJECTS", "Hidan Objects", "Hidan Objects"),
    ("OBJECT_HORSE_GANON", "Horse Ganon", "Horse Ganon"),
    ("OBJECT_OA2", "Oa2", "Oa2"),
    ("OBJECT_SPOT00_OBJECTS", "Spot00 Objects", "Spot00 Objects"),
    ("OBJECT_MB", "Mb", "Mb"),
    ("OBJECT_BOMBF", "Bombf", "Bombf"),
    ("OBJECT_SK2", "Sk2", "Sk2"),
    ("OBJECT_OE1", "Oe1", "Oe1"),
    ("OBJECT_OE_ANIME", "Oe Anime", "Oe Anime"),
    ("OBJECT_OE2", "Oe2", "Oe2"),
    ("OBJECT_YDAN_OBJECTS", "Ydan Objects", "Ydan Objects"),
    ("OBJECT_GND", "Gnd", "Gnd"),
    ("OBJECT_AM", "Am", "Am"),
    ("OBJECT_DEKUBABA", "Dekubaba", "Dekubaba"),
    ("OBJECT_OA3", "Oa3", "Oa3"),
    ("OBJECT_OA4", "Oa4", "Oa4"),
    ("OBJECT_OA5", "Oa5", "Oa5"),
    ("OBJECT_OA6", "Oa6", "Oa6"),
    ("OBJECT_OA7", "Oa7", "Oa7"),
    ("OBJECT_JJ", "Jj", "Jj"),
    ("OBJECT_OA8", "Oa8", "Oa8"),
    ("OBJECT_OA9", "Oa9", "Oa9"),
    ("OBJECT_OB2", "Ob2", "Ob2"),
    ("OBJECT_OB3", "Ob3", "Ob3"),
    ("OBJECT_OB4", "Ob4", "Ob4"),
    ("OBJECT_HORSE_ZELDA", "Horse Zelda", "Horse Zelda"),
    ("OBJECT_OPENING_DEMO1", "Opening Demo1", "Opening Demo1"),
    ("OBJECT_WARP1", "Warp1", "Warp1"),
    ("OBJECT_B_HEART", "B Heart", "B Heart"),
    ("OBJECT_DEKUNUTS", "Dekunuts", "Dekunuts"),
    ("OBJECT_OE3", "Oe3", "Oe3"),
    ("OBJECT_OE4", "Oe4", "Oe4"),
    ("OBJECT_MENKURI_OBJECTS", "Menkuri Objects", "Menkuri Objects"),
    ("OBJECT_OE5", "Oe5", "Oe5"),
    ("OBJECT_OE6", "Oe6", "Oe6"),
    ("OBJECT_OE7", "Oe7", "Oe7"),
    ("OBJECT_OE8", "Oe8", "Oe8"),
    ("OBJECT_OE9", "Oe9", "Oe9"),
    ("OBJECT_OE10", "Oe10", "Oe10"),
    ("OBJECT_OE11", "Oe11", "Oe11"),
    ("OBJECT_OE12", "Oe12", "Oe12"),
    ("OBJECT_VALI", "Vali", "Vali"),
    ("OBJECT_OA10", "Oa10", "Oa10"),
    ("OBJECT_OA11", "Oa11", "Oa11"),
    ("OBJECT_MIZU_OBJECTS", "Mizu Objects", "Mizu Objects"),
    ("OBJECT_FHG", "Fhg", "Fhg"),
    ("OBJECT_OSSAN", "Ossan", "Ossan"),
    ("OBJECT_MORI_HINERI1", "Mori Hineri1", "Mori Hineri1"),
    ("OBJECT_BB", "Bb", "Bb"),
    ("OBJECT_TOKI_OBJECTS", "Toki Objects", "Toki Objects"),
    ("OBJECT_YUKABYUN", "Yukabyun", "Yukabyun"),
    ("OBJECT_ZL2", "Zl2", "Zl2"),
    ("OBJECT_MJIN", "Mjin", "Mjin"),
    ("OBJECT_MJIN_FLASH", "Mjin Flash", "Mjin Flash"),
    ("OBJECT_MJIN_DARK", "Mjin Dark", "Mjin Dark"),
    ("OBJECT_MJIN_FLAME", "Mjin Flame", "Mjin Flame"),
    ("OBJECT_MJIN_ICE", "Mjin Ice", "Mjin Ice"),
    ("OBJECT_MJIN_SOUL", "Mjin Soul", "Mjin Soul"),
    ("OBJECT_MJIN_WIND", "Mjin Wind", "Mjin Wind"),
    ("OBJECT_MJIN_OKA", "Mjin Oka", "Mjin Oka"),
    ("OBJECT_HAKA_OBJECTS", "Haka Objects", "Haka Objects"),
    ("OBJECT_SPOT06_OBJECTS", "Spot06 Objects", "Spot06 Objects"),
    ("OBJECT_ICE_OBJECTS", "Ice Objects", "Ice Objects"),
    ("OBJECT_RELAY_OBJECTS", "Relay Objects", "Relay Objects"),
    ("OBJECT_PO_FIELD", "Po Field", "Po Field"),
    ("OBJECT_PO_COMPOSER", "Po Composer", "Po Composer"),
    ("OBJECT_MORI_HINERI1A", "Mori Hineri1a", "Mori Hineri1a"),
    ("OBJECT_MORI_HINERI2", "Mori Hineri2", "Mori Hineri2"),
    ("OBJECT_MORI_HINERI2A", "Mori Hineri2a", "Mori Hineri2a"),
    ("OBJECT_MORI_OBJECTS", "Mori Objects", "Mori Objects"),
    ("OBJECT_MORI_TEX", "Mori Tex", "Mori Tex"),
    ("OBJECT_SPOT08_OBJ", "Spot08 Obj", "Spot08 Obj"),
    ("OBJECT_WARP2", "Warp2", "Warp2"),
    ("OBJECT_HATA", "Hata", "Hata"),
    ("OBJECT_BIRD", "Bird", "Bird"),
    ("OBJECT_WOOD02", "Wood02", "Wood02"),
    ("OBJECT_LIGHTBOX", "Lightbox", "Lightbox"),
    ("OBJECT_PU_BOX", "Pu Box", "Pu Box"),
    ("OBJECT_TRAP", "Trap", "Trap"),
    ("OBJECT_VASE", "Vase", "Vase"),
    ("OBJECT_IM", "Im", "Im"),
    ("OBJECT_TA", "Ta", "Ta"),
    ("OBJECT_TK", "Tk", "Tk"),
    ("OBJECT_XC", "Xc", "Xc"),
    ("OBJECT_VM", "Vm", "Vm"),
    ("OBJECT_BV", "Bv", "Bv"),
    ("OBJECT_HAKACH_OBJECTS", "Hakach Objects", "Hakach Objects"),
    ("OBJECT_EFC_CRYSTAL_LIGHT", "Efc Crystal Light", "Efc Crystal Light"),
    ("OBJECT_EFC_FIRE_BALL", "Efc Fire Ball", "Efc Fire Ball"),
    ("OBJECT_EFC_FLASH", "Efc Flash", "Efc Flash"),
    ("OBJECT_EFC_LGT_SHOWER", "Efc Lgt Shower", "Efc Lgt Shower"),
    ("OBJECT_EFC_STAR_FIELD", "Efc Star Field", "Efc Star Field"),
    ("OBJECT_GOD_LGT", "God Lgt", "God Lgt"),
    ("OBJECT_LIGHT_RING", "Light Ring", "Light Ring"),
    ("OBJECT_TRIFORCE_SPOT", "Triforce Spot", "Triforce Spot"),
    ("OBJECT_BDAN_OBJECTS", "Bdan Objects", "Bdan Objects"),
    ("OBJECT_SD", "Sd", "Sd"),
    ("OBJECT_RD", "Rd", "Rd"),
    ("OBJECT_PO_SISTERS", "Po Sisters", "Po Sisters"),
    ("OBJECT_HEAVY_OBJECT", "Heavy Object", "Heavy Object"),
    ("OBJECT_GNDD", "Gndd", "Gndd"),
    ("OBJECT_FD", "Fd", "Fd"),
    ("OBJECT_DU", "Du", "Du"),
    ("OBJECT_FW", "Fw", "Fw"),
    ("OBJECT_MEDAL", "Medal", "Medal"),
    ("OBJECT_HORSE_LINK_CHILD", "Horse Link Child", "Horse Link Child"),
    ("OBJECT_SPOT02_OBJECTS", "Spot02 Objects", "Spot02 Objects"),
    ("OBJECT_HAKA", "Haka", "Haka"),
    ("OBJECT_RU1", "Ru1", "Ru1"),
    ("OBJECT_SYOKUDAI", "Syokudai", "Syokudai"),
    ("OBJECT_FD2", "Fd2", "Fd2"),
    ("OBJECT_DH", "Dh", "Dh"),
    ("OBJECT_RL", "Rl", "Rl"),
    ("OBJECT_EFC_TW", "Efc Tw", "Efc Tw"),
    ("OBJECT_DEMO_TRE_LGT", "Demo Tre Lgt", "Demo Tre Lgt"),
    ("OBJECT_GI_KEY", "Gi Key", "Gi Key"),
    ("OBJECT_MIR_RAY", "Mir Ray", "Mir Ray"),
    ("OBJECT_BROB", "Brob", "Brob"),
    ("OBJECT_GI_JEWEL", "Gi Jewel", "Gi Jewel"),
    ("OBJECT_SPOT09_OBJ", "Spot09 Obj", "Spot09 Obj"),
    ("OBJECT_SPOT18_OBJ", "Spot18 Obj", "Spot18 Obj"),
    ("OBJECT_BDOOR", "Bdoor", "Bdoor"),
    ("OBJECT_SPOT17_OBJ", "Spot17 Obj", "Spot17 Obj"),
    ("OBJECT_SHOP_DUNGEN", "Shop Dungen", "Shop Dungen"),
    ("OBJECT_NB", "Nb", "Nb"),
    ("OBJECT_MO", "Mo", "Mo"),
    ("OBJECT_SB", "Sb", "Sb"),
    ("OBJECT_GI_MELODY", "Gi Melody", "Gi Melody"),
    ("OBJECT_GI_HEART", "Gi Heart", "Gi Heart"),
    ("OBJECT_GI_COMPASS", "Gi Compass", "Gi Compass"),
    ("OBJECT_GI_BOSSKEY", "Gi Bosskey", "Gi Bosskey"),
    ("OBJECT_GI_MEDAL", "Gi Medal", "Gi Medal"),
    ("OBJECT_GI_NUTS", "Gi Nuts", "Gi Nuts"),
    ("OBJECT_SA", "Sa", "Sa"),
    ("OBJECT_GI_HEARTS", "Gi Hearts", "Gi Hearts"),
    ("OBJECT_GI_ARROWCASE", "Gi Arrowcase", "Gi Arrowcase"),
    ("OBJECT_GI_BOMBPOUCH", "Gi Bombpouch", "Gi Bombpouch"),
    ("OBJECT_IN", "In", "In"),
    ("OBJECT_TR", "Tr", "Tr"),
    ("OBJECT_SPOT16_OBJ", "Spot16 Obj", "Spot16 Obj"),
    ("OBJECT_OE1S", "Oe1s", "Oe1s"),
    ("OBJECT_OE4S", "Oe4s", "Oe4s"),
    ("OBJECT_OS_ANIME", "Os Anime", "Os Anime"),
    ("OBJECT_GI_BOTTLE", "Gi Bottle", "Gi Bottle"),
    ("OBJECT_GI_STICK", "Gi Stick", "Gi Stick"),
    ("OBJECT_GI_MAP", "Gi Map", "Gi Map"),
    ("OBJECT_OF1D_MAP", "Of1d Map", "Of1d Map"),
    ("OBJECT_RU2", "Ru2", "Ru2"),
    ("OBJECT_GI_SHIELD_1", "Gi Shield 1", "Gi Shield 1"),
    ("OBJECT_DEKUJR", "Dekujr", "Dekujr"),
    ("OBJECT_GI_MAGICPOT", "Gi Magicpot", "Gi Magicpot"),
    ("OBJECT_GI_BOMB_1", "Gi Bomb 1", "Gi Bomb 1"),
    ("OBJECT_OF1S", "Of1s", "Of1s"),
    ("OBJECT_MA2", "Ma2", "Ma2"),
    ("OBJECT_GI_PURSE", "Gi Purse", "Gi Purse"),
    ("OBJECT_HNI", "Hni", "Hni"),
    ("OBJECT_TW", "Tw", "Tw"),
    ("OBJECT_RR", "Rr", "Rr"),
    ("OBJECT_BXA", "Bxa", "Bxa"),
    ("OBJECT_ANUBICE", "Anubice", "Anubice"),
    ("OBJECT_GI_GERUDO", "Gi Gerudo", "Gi Gerudo"),
    ("OBJECT_GI_ARROW", "Gi Arrow", "Gi Arrow"),
    ("OBJECT_GI_BOMB_2", "Gi Bomb 2", "Gi Bomb 2"),
    ("OBJECT_GI_EGG", "Gi Egg", "Gi Egg"),
    ("OBJECT_GI_SCALE", "Gi Scale", "Gi Scale"),
    ("OBJECT_GI_SHIELD_2", "Gi Shield 2", "Gi Shield 2"),
    ("OBJECT_GI_HOOKSHOT", "Gi Hookshot", "Gi Hookshot"),
    ("OBJECT_GI_OCARINA", "Gi Ocarina", "Gi Ocarina"),
    ("OBJECT_GI_MILK", "Gi Milk", "Gi Milk"),
    ("OBJECT_MA1", "Ma1", "Ma1"),
    ("OBJECT_GANON", "Ganon", "Ganon"),
    ("OBJECT_SST", "Sst", "Sst"),
    ("OBJECT_NY_UNUSED", "Ny Unused", "Ny Unused"),
    ("OBJECT_NY", "Ny", "Ny"),
    ("OBJECT_FR", "Fr", "Fr"),
    ("OBJECT_GI_PACHINKO", "Gi Pachinko", "Gi Pachinko"),
    ("OBJECT_GI_BOOMERANG", "Gi Boomerang", "Gi Boomerang"),
    ("OBJECT_GI_BOW", "Gi Bow", "Gi Bow"),
    ("OBJECT_GI_GLASSES", "Gi Glasses", "Gi Glasses"),
    ("OBJECT_GI_LIQUID", "Gi Liquid", "Gi Liquid"),
    ("OBJECT_ANI", "Ani", "Ani"),
    ("OBJECT_DEMO_6K", "Demo 6k", "Demo 6k"),
    ("OBJECT_GI_SHIELD_3", "Gi Shield 3", "Gi Shield 3"),
    ("OBJECT_GI_LETTER", "Gi Letter", "Gi Letter"),
    ("OBJECT_SPOT15_OBJ", "Spot15 Obj", "Spot15 Obj"),
    ("OBJECT_JYA_OBJ", "Jya Obj", "Jya Obj"),
    ("OBJECT_GI_CLOTHES", "Gi Clothes", "Gi Clothes"),
    ("OBJECT_GI_BEAN", "Gi Bean", "Gi Bean"),
    ("OBJECT_GI_FISH", "Gi Fish", "Gi Fish"),
    ("OBJECT_GI_SAW", "Gi Saw", "Gi Saw"),
    ("OBJECT_GI_HAMMER", "Gi Hammer", "Gi Hammer"),
    ("OBJECT_GI_GRASS", "Gi Grass", "Gi Grass"),
    ("OBJECT_GI_LONGSWORD", "Gi Longsword", "Gi Longsword"),
    ("OBJECT_SPOT01_OBJECTS", "Spot01 Objects", "Spot01 Objects"),
    ("OBJECT_MD_UNUSED", "Md Unused", "Md Unused"),
    ("OBJECT_MD", "Md", "Md"),
    ("OBJECT_KM1", "Km1", "Km1"),
    ("OBJECT_KW1", "Kw1", "Kw1"),
    ("OBJECT_ZO", "Zo", "Zo"),
    ("OBJECT_KZ", "Kz", "Kz"),
    ("OBJECT_UMAJUMP", "Umajump", "Umajump"),
    ("OBJECT_MASTERKOKIRI", "Masterkokiri", "Masterkokiri"),
    ("OBJECT_MASTERKOKIRIHEAD", "Masterkokirihead", "Masterkokirihead"),
    ("OBJECT_MASTERGOLON", "Mastergolon", "Mastergolon"),
    ("OBJECT_MASTERZOORA", "Masterzoora", "Masterzoora"),
    ("OBJECT_AOB", "Aob", "Aob"),
    ("OBJECT_IK", "Ik", "Ik"),
    ("OBJECT_AHG", "Ahg", "Ahg"),
    ("OBJECT_CNE", "Cne", "Cne"),
    ("OBJECT_GI_NIWATORI", "Gi Niwatori", "Gi Niwatori"),
    ("OBJECT_SKJ", "Skj", "Skj"),
    ("OBJECT_GI_BOTTLE_LETTER", "Gi Bottle Letter", "Gi Bottle Letter"),
    ("OBJECT_BJI", "Bji", "Bji"),
    ("OBJECT_BBA", "Bba", "Bba"),
    ("OBJECT_GI_OCARINA_0", "Gi Ocarina 0", "Gi Ocarina 0"),
    ("OBJECT_DS", "Ds", "Ds"),
    ("OBJECT_ANE", "Ane", "Ane"),
    ("OBJECT_BOJ", "Boj", "Boj"),
    ("OBJECT_SPOT03_OBJECT", "Spot03 Object", "Spot03 Object"),
    ("OBJECT_SPOT07_OBJECT", "Spot07 Object", "Spot07 Object"),
    ("OBJECT_FZ", "Fz", "Fz"),
    ("OBJECT_BOB", "Bob", "Bob"),
    ("OBJECT_GE1", "Ge1", "Ge1"),
    ("OBJECT_YABUSAME_POINT", "Yabusame Point", "Yabusame Point"),
    ("OBJECT_GI_BOOTS_2", "Gi Boots 2", "Gi Boots 2"),
    ("OBJECT_GI_SEED", "Gi Seed", "Gi Seed"),
    ("OBJECT_GND_MAGIC", "Gnd Magic", "Gnd Magic"),
    ("OBJECT_D_ELEVATOR", "D Elevator", "D Elevator"),
    ("OBJECT_D_HSBLOCK", "D Hsblock", "D Hsblock"),
    ("OBJECT_D_LIFT", "D Lift", "D Lift"),
    ("OBJECT_MAMENOKI", "Mamenoki", "Mamenoki"),
    ("OBJECT_GOROIWA", "Goroiwa", "Goroiwa"),
    ("OBJECT_TORYO", "Toryo", "Toryo"),
    ("OBJECT_DAIKU", "Daiku", "Daiku"),
    ("OBJECT_NWC", "Nwc", "Nwc"),
    ("OBJECT_BLKOBJ", "Blkobj", "Blkobj"),
    ("OBJECT_GM", "Gm", "Gm"),
    ("OBJECT_MS", "Ms", "Ms"),
    ("OBJECT_HS", "Hs", "Hs"),
    ("OBJECT_INGATE", "Ingate", "Ingate"),
    ("OBJECT_LIGHTSWITCH", "Lightswitch", "Lightswitch"),
    ("OBJECT_KUSA", "Kusa", "Kusa"),
    ("OBJECT_TSUBO", "Tsubo", "Tsubo"),
    ("OBJECT_GI_GLOVES", "Gi Gloves", "Gi Gloves"),
    ("OBJECT_GI_COIN", "Gi Coin", "Gi Coin"),
    ("OBJECT_KANBAN", "Kanban", "Kanban"),
    ("OBJECT_GJYO_OBJECTS", "Gjyo Objects", "Gjyo Objects"),
    ("OBJECT_OWL", "Owl", "Owl"),
    ("OBJECT_MK", "Mk", "Mk"),
    ("OBJECT_FU", "Fu", "Fu"),
    ("OBJECT_GI_KI_TAN_MASK", "Gi Ki Tan Mask", "Gi Ki Tan Mask"),
    ("OBJECT_GI_REDEAD_MASK", "Gi Redead Mask", "Gi Redead Mask"),
    ("OBJECT_GI_SKJ_MASK", "Gi Skj Mask", "Gi Skj Mask"),
    ("OBJECT_GI_RABIT_MASK", "Gi Rabit Mask", "Gi Rabit Mask"),
    ("OBJECT_GI_TRUTH_MASK", "Gi Truth Mask", "Gi Truth Mask"),
    ("OBJECT_GANON_OBJECTS", "Ganon Objects", "Ganon Objects"),
    ("OBJECT_SIOFUKI", "Siofuki", "Siofuki"),
    ("OBJECT_STREAM", "Stream", "Stream"),
    ("OBJECT_MM", "Mm", "Mm"),
    ("OBJECT_FA", "Fa", "Fa"),
    ("OBJECT_OS", "Os", "Os"),
    ("OBJECT_GI_EYE_LOTION", "Gi Eye Lotion", "Gi Eye Lotion"),
    ("OBJECT_GI_POWDER", "Gi Powder", "Gi Powder"),
    ("OBJECT_GI_MUSHROOM", "Gi Mushroom", "Gi Mushroom"),
    ("OBJECT_GI_TICKETSTONE", "Gi Ticketstone", "Gi Ticketstone"),
    ("OBJECT_GI_BROKENSWORD", "Gi Brokensword", "Gi Brokensword"),
    ("OBJECT_JS", "Js", "Js"),
    ("OBJECT_CS", "Cs", "Cs"),
    ("OBJECT_GI_PRESCRIPTION", "Gi Prescription", "Gi Prescription"),
    ("OBJECT_GI_BRACELET", "Gi Bracelet", "Gi Bracelet"),
    ("OBJECT_GI_SOLDOUT", "Gi Soldout", "Gi Soldout"),
    ("OBJECT_GI_FROG", "Gi Frog", "Gi Frog"),
    ("OBJECT_MAG", "Mag", "Mag"),
    ("OBJECT_DOOR_GERUDO", "Door Gerudo", "Door Gerudo"),
    ("OBJECT_GT", "Gt", "Gt"),
    ("OBJECT_EFC_ERUPC", "Efc Erupc", "Efc Erupc"),
    ("OBJECT_ZL2_ANIME1", "Zl2 Anime1", "Zl2 Anime1"),
    ("OBJECT_ZL2_ANIME2", "Zl2 Anime2", "Zl2 Anime2"),
    ("OBJECT_GI_GOLONMASK", "Gi Golonmask", "Gi Golonmask"),
    ("OBJECT_GI_ZORAMASK", "Gi Zoramask", "Gi Zoramask"),
    ("OBJECT_GI_GERUDOMASK", "Gi Gerudomask", "Gi Gerudomask"),
    ("OBJECT_GANON2", "Ganon2", "Ganon2"),
    ("OBJECT_KA", "Ka", "Ka"),
    ("OBJECT_TS", "Ts", "Ts"),
    ("OBJECT_ZG", "Zg", "Zg"),
    ("OBJECT_GI_HOVERBOOTS", "Gi Hoverboots", "Gi Hoverboots"),
    ("OBJECT_GI_M_ARROW", "Gi M Arrow", "Gi M Arrow"),
    ("OBJECT_DS2", "Ds2", "Ds2"),
    ("OBJECT_EC", "Ec", "Ec"),
    ("OBJECT_FISH", "Fish", "Fish"),
    ("OBJECT_GI_SUTARU", "Gi Sutaru", "Gi Sutaru"),
    ("OBJECT_GI_GODDESS", "Gi Goddess", "Gi Goddess"),
    ("OBJECT_SSH", "Ssh", "Ssh"),
    ("OBJECT_BIGOKUTA", "Bigokuta", "Bigokuta"),
    ("OBJECT_BG", "Bg", "Bg"),
    ("OBJECT_SPOT05_OBJECTS", "Spot05 Objects", "Spot05 Objects"),
    ("OBJECT_SPOT12_OBJ", "Spot12 Obj", "Spot12 Obj"),
    ("OBJECT_BOMBIWA", "Bombiwa", "Bombiwa"),
    ("OBJECT_HINTNUTS", "Hintnuts", "Hintnuts"),
    ("OBJECT_RS", "Rs", "Rs"),
    ("OBJECT_SPOT00_BREAK", "Spot00 Break", "Spot00 Break"),
    ("OBJECT_GLA", "Gla", "Gla"),
    ("OBJECT_SHOPNUTS", "Shopnuts", "Shopnuts"),
    ("OBJECT_GELDB", "Geldb", "Geldb"),
    ("OBJECT_GR", "Gr", "Gr"),
    ("OBJECT_DOG", "Dog", "Dog"),
    ("OBJECT_JYA_IRON", "Jya Iron", "Jya Iron"),
    ("OBJECT_JYA_DOOR", "Jya Door", "Jya Door"),
    ("OBJECT_SPOT11_OBJ", "Spot11 Obj", "Spot11 Obj"),
    ("OBJECT_KIBAKO2", "Kibako2", "Kibako2"),
    ("OBJECT_DNS", "Dns", "Dns"),
    ("OBJECT_DNK", "Dnk", "Dnk"),
    ("OBJECT_GI_FIRE", "Gi Fire", "Gi Fire"),
    ("OBJECT_GI_INSECT", "Gi Insect", "Gi Insect"),
    ("OBJECT_GI_BUTTERFLY", "Gi Butterfly", "Gi Butterfly"),
    ("OBJECT_GI_GHOST", "Gi Ghost", "Gi Ghost"),
    ("OBJECT_GI_SOUL", "Gi Soul", "Gi Soul"),
    ("OBJECT_BOWL", "Bowl", "Bowl"),
    ("OBJECT_DEMO_KEKKAI", "Demo Kekkai", "Demo Kekkai"),
    ("OBJECT_EFC_DOUGHNUT", "Efc Doughnut", "Efc Doughnut"),
    ("OBJECT_GI_DEKUPOUCH", "Gi Dekupouch", "Gi Dekupouch"),
    ("OBJECT_GANON_ANIME1", "Ganon Anime1", "Ganon Anime1"),
    ("OBJECT_GANON_ANIME2", "Ganon Anime2", "Ganon Anime2"),
    ("OBJECT_GANON_ANIME3", "Ganon Anime3", "Ganon Anime3"),
    ("OBJECT_GI_RUPY", "Gi Rupy", "Gi Rupy"),
    ("OBJECT_SPOT01_MATOYA", "Spot01 Matoya", "Spot01 Matoya"),
    ("OBJECT_SPOT01_MATOYAB", "Spot01 Matoyab", "Spot01 Matoyab"),
    ("OBJECT_MU", "Mu", "Mu"),
    ("OBJECT_WF", "Wf", "Wf"),
    ("OBJECT_SKB", "Skb", "Skb"),
    ("OBJECT_GJ", "Gj", "Gj"),
    ("OBJECT_GEFF", "Geff", "Geff"),
    ("OBJECT_HAKA_DOOR", "Haka Door", "Haka Door"),
    ("OBJECT_GS", "Gs", "Gs"),
    ("OBJECT_PS", "Ps", "Ps"),
    ("OBJECT_BWALL", "Bwall", "Bwall"),
    ("OBJECT_COW", "Cow", "Cow"),
    ("OBJECT_COB", "Cob", "Cob"),
    ("OBJECT_GI_SWORD_1", "Gi Sword 1", "Gi Sword 1"),
    ("OBJECT_DOOR_KILLER", "Door Killer", "Door Killer"),
    ("OBJECT_OUKE_HAKA", "Ouke Haka", "Ouke Haka"),
    ("OBJECT_TIMEBLOCK", "Timeblock", "Timeblock"),
]

ootEnumGlobalObject = [
    ("Custom", "Custom", "Custom"),
    ("0x0000", "None", "None"),
    ("0x0002", "Overworld", "gameplay_field_keep"),
    ("0x0003", "Dungeon", "gameplay_dangeon_keep"),
]

ootEnumNaviHints = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "None", "None"),
    ("0x01", "Overworld", "elf_message_field"),
    ("0x02", "Dungeon", "elf_message_ydan"),
]

ootEnumTransitionAnims = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "Spiky", "Spiky"),
    ("0x01", "Triforce", "Triforce"),
    ("0x02", "Slow Black Fade", "Slow Black Fade"),
    ("0x03", "Slow Day/White, Slow Night/Black Fade", "Slow Day/White, Slow Night/Black Fade"),
    ("0x04", "Fast Day/Black, Slow Night/Black Fade", "Fast Day/Black, Slow Night/Black Fade"),
    ("0x05", "Fast Day/White, Slow Night/Black Fade", "Fast Day/White, Slow Night/Black Fade"),
    ("0x06", "Very Slow Day/White, Slow Night/Black Fade", "Very Slow Day/White, Slow Night/Black Fade"),
    ("0x07", "Very Slow Day/White, Slow Night/Black Fade", "Very Slow Day/White, Slow Night/Black Fade"),
    ("0x0E", "Slow Sandstorm Fade", "Slow Sandstorm Fade"),
    ("0x0F", "Fast Sandstorm Fade", "Fast Sandstorm Fade"),
    ("0x20", "Iris Fade", "Iris Fade"),
    ("0x2C", "Shortcut Transition", "Shortcut Transition"),
]

# The order of this list matters (normal OoT scene order as defined by ``scene_table.h``)
ootEnumSceneID = [
    ("Custom", "Custom", "Custom"),
    ("SCENE_YDAN", "Inside the Deku Tree (Ydan)", "Ydan"),
    ("SCENE_DDAN", "Dodongo's Cavern (Ddan)", "Ddan"),
    ("SCENE_BDAN", "Inside Jabu Jabu's Belly (Bdan)", "Bdan"),
    ("SCENE_BMORI1", "Forest Temple (Bmori1)", "Bmori1"),
    ("SCENE_HIDAN", "Fire Temple (Hidan)", "Hidan"),
    ("SCENE_MIZUSIN", "Water Temple (Mizusin)", "Mizusin"),
    ("SCENE_JYASINZOU", "Spirit Temple (Jyasinzou)", "Jyasinzou"),
    ("SCENE_HAKADAN", "Shadow Temple (Hakadan)", "Hakadan"),
    ("SCENE_HAKADANCH", "Bottom of the Well (Hakadanch)", "Hakadanch"),
    ("SCENE_ICE_DOUKUTO", "Ice Cavern (Ice Doukuto)", "Ice Doukuto"),
    ("SCENE_GANON", "Ganon's Tower (Ganon)", "Ganon"),
    ("SCENE_MEN", "Gerudo Training Ground (Men)", "Men"),
    ("SCENE_GERUDOWAY", "Thieves' Hideout (Gerudoway)", "Gerudoway"),
    ("SCENE_GANONTIKA", "Inside Ganon's Castle (Ganontika)", "Ganontika"),
    ("SCENE_GANON_SONOGO", "Ganon's Tower (Collapsing) (Ganon Sonogo)", "Ganon Sonogo"),
    ("SCENE_GANONTIKA_SONOGO", "Inside Ganon's Castle (Collapsing) (Ganontika Sonogo)", "Ganontika Sonogo"),
    ("SCENE_TAKARAYA", "Treasure Chest Shop (Takaraya)", "Takaraya"),
    ("SCENE_YDAN_BOSS", "Gohma's Lair (Ydan Boss)", "Ydan Boss"),
    ("SCENE_DDAN_BOSS", "King Dodongo's Lair (Ddan Boss)", "Ddan Boss"),
    ("SCENE_BDAN_BOSS", "Barinade's Lair (Bdan Boss)", "Bdan Boss"),
    ("SCENE_MORIBOSSROOM", "Phantom Ganon's Lair (Moribossroom)", "Moribossroom"),
    ("SCENE_FIRE_BS", "Volvagia's Lair (Fire Bs)", "Fire Bs"),
    ("SCENE_MIZUSIN_BS", "Morpha's Lair (Mizusin Bs)", "Mizusin Bs"),
    ("SCENE_JYASINBOSS", "Twinrova's Lair & Iron Knuckle Mini-Boss Room (Jyasinboss)", "Jyasinboss"),
    ("SCENE_HAKADAN_BS", "Bongo Bongo's Lair (Hakadan Bs)", "Hakadan Bs"),
    ("SCENE_GANON_BOSS", "Ganondorf's Lair (Ganon Boss)", "Ganon Boss"),
    ("SCENE_GANON_FINAL", "Ganondorf's Death Scene (Tower Escape Exterior) (Ganon Final)", "Ganon Final"),
    ("SCENE_ENTRA", "Market Entrance (Child - Day) (Entra)", "Entra"),
    ("SCENE_ENTRA_N", "Market Entrance (Child - Night) (Entra N)", "Entra N"),
    ("SCENE_ENRUI", "Market Entrance (Ruins) (Enrui)", "Enrui"),
    ("SCENE_MARKET_ALLEY", "Back Alley (Day) (Market Alley)", "Market Alley"),
    ("SCENE_MARKET_ALLEY_N", "Back Alley (Night) (Market Alley N)", "Market Alley N"),
    ("SCENE_MARKET_DAY", "Market (Child - Day) (Market Day)", "Market Day"),
    ("SCENE_MARKET_NIGHT", "Market (Child - Night) (Market Night)", "Market Night"),
    ("SCENE_MARKET_RUINS", "Market (Ruins) (Market Ruins)", "Market Ruins"),
    ("SCENE_SHRINE", "Temple of Time Exterior (Day) (Shrine)", "Shrine"),
    ("SCENE_SHRINE_N", "Temple of Time Exterior (Night) (Shrine N)", "Shrine N"),
    ("SCENE_SHRINE_R", "Temple of Time Exterior (Ruins) (Shrine R)", "Shrine R"),
    ("SCENE_KOKIRI_HOME", "Know-It-All Brothers' House (Kokiri Home)", "Kokiri Home"),
    ("SCENE_KOKIRI_HOME3", "Twins' House (Kokiri Home3)", "Kokiri Home3"),
    ("SCENE_KOKIRI_HOME4", "Mido's House (Kokiri Home4)", "Kokiri Home4"),
    ("SCENE_KOKIRI_HOME5", "Saria's House (Kokiri Home5)", "Kokiri Home5"),
    ("SCENE_KAKARIKO", "Carpenter Boss's House (Kakariko)", "Kakariko"),
    ("SCENE_KAKARIKO3", "Back Alley House (Man in Green) (Kakariko3)", "Kakariko3"),
    ("SCENE_SHOP1", "Bazaar (Shop1)", "Shop1"),
    ("SCENE_KOKIRI_SHOP", "Kokiri Shop (Kokiri Shop)", "Kokiri Shop"),
    ("SCENE_GOLON", "Goron Shop (Golon)", "Golon"),
    ("SCENE_ZOORA", "Zora Shop (Zoora)", "Zoora"),
    ("SCENE_DRAG", "Kakariko Potion Shop (Drag)", "Drag"),
    ("SCENE_ALLEY_SHOP", "Market Potion Shop (Alley Shop)", "Alley Shop"),
    ("SCENE_NIGHT_SHOP", "Bombchu Shop (Night Shop)", "Night Shop"),
    ("SCENE_FACE_SHOP", "Happy Mask Shop (Face Shop)", "Face Shop"),
    ("SCENE_LINK_HOME", "Link's House (Link Home)", "Link Home"),
    ("SCENE_IMPA", "Back Alley House (Dog Lady) (Impa)", "Impa"),
    ("SCENE_MALON_STABLE", "Stable (Malon Stable)", "Malon Stable"),
    ("SCENE_LABO", "Impa's House (Labo)", "Labo"),
    ("SCENE_HYLIA_LABO", "Lakeside Laboratory (Hylia Labo)", "Hylia Labo"),
    ("SCENE_TENT", "Carpenters' Tent (Tent)", "Tent"),
    ("SCENE_HUT", "Gravekeeper's Hut (Hut)", "Hut"),
    ("SCENE_DAIYOUSEI_IZUMI", "Great Fairy's Fountain (Upgrades) (Daiyousei Izumi)", "Daiyousei Izumi"),
    ("SCENE_YOUSEI_IZUMI_TATE", "Fairy's Fountain (Healing Fairies) (Yousei Izumi Tate)", "Yousei Izumi Tate"),
    ("SCENE_YOUSEI_IZUMI_YOKO", "Great Fairy's Fountain (Spells) (Yousei Izumi Yoko)", "Yousei Izumi Yoko"),
    ("SCENE_KAKUSIANA", "Grottos (Kakusiana)", "Kakusiana"),
    ("SCENE_HAKAANA", "Grave (Redead) (Hakaana)", "Hakaana"),
    ("SCENE_HAKAANA2", "Grave (Fairy's Fountain) (Hakaana2)", "Hakaana2"),
    ("SCENE_HAKAANA_OUKE", "Royal Family's Tomb (Hakaana Ouke)", "Hakaana Ouke"),
    ("SCENE_SYATEKIJYOU", "Shooting Gallery (Syatekijyou)", "Syatekijyou"),
    ("SCENE_TOKINOMA", "Temple of Time (Tokinoma)", "Tokinoma"),
    ("SCENE_KENJYANOMA", "Chamber of the Sages (Kenjyanoma)", "Kenjyanoma"),
    ("SCENE_HAIRAL_NIWA", "Castle Hedge Maze (Day) (Hairal Niwa)", "Hairal Niwa"),
    ("SCENE_HAIRAL_NIWA_N", "Castle Hedge Maze (Night) (Hairal Niwa N)", "Hairal Niwa N"),
    ("SCENE_HIRAL_DEMO", "Cutscene Map (Hiral Demo)", "Hiral Demo"),
    ("SCENE_HAKASITARELAY", "Dampé's Grave & Windmill (Hakasitarelay)", "Hakasitarelay"),
    ("SCENE_TURIBORI", "Fishing Pond (Turibori)", "Turibori"),
    ("SCENE_NAKANIWA", "Castle Courtyard (Nakaniwa)", "Nakaniwa"),
    ("SCENE_BOWLING", "Bombchu Bowling Alley (Bowling)", "Bowling"),
    ("SCENE_SOUKO", "Lon Lon Ranch House & Tower (Souko)", "Souko"),
    ("SCENE_MIHARIGOYA", "Guard House (Miharigoya)", "Miharigoya"),
    ("SCENE_MAHOUYA", "Granny's Potion Shop (Mahouya)", "Mahouya"),
    ("SCENE_GANON_DEMO", "Ganon's Tower Collapse & Battle Arena (Ganon Demo)", "Ganon Demo"),
    ("SCENE_KINSUTA", "House of Skulltula (Kinsuta)", "Kinsuta"),
    ("SCENE_SPOT00", "Hyrule Field (Spot00)", "Spot00"),
    ("SCENE_SPOT01", "Kakariko Village (Spot01)", "Spot01"),
    ("SCENE_SPOT02", "Graveyard (Spot02)", "Spot02"),
    ("SCENE_SPOT03", "Zora's River (Spot03)", "Spot03"),
    ("SCENE_SPOT04", "Kokiri Forest (Spot04)", "Spot04"),
    ("SCENE_SPOT05", "Sacred Forest Meadow (Spot05)", "Spot05"),
    ("SCENE_SPOT06", "Lake Hylia (Spot06)", "Spot06"),
    ("SCENE_SPOT07", "Zora's Domain (Spot07)", "Spot07"),
    ("SCENE_SPOT08", "Zora's Fountain (Spot08)", "Spot08"),
    ("SCENE_SPOT09", "Gerudo Valley (Spot09)", "Spot09"),
    ("SCENE_SPOT10", "Lost Woods (Spot10)", "Spot10"),
    ("SCENE_SPOT11", "Desert Colossus (Spot11)", "Spot11"),
    ("SCENE_SPOT12", "Gerudo's Fortress (Spot12)", "Spot12"),
    ("SCENE_SPOT13", "Haunted Wasteland (Spot13)", "Spot13"),
    ("SCENE_SPOT15", "Hyrule Castle (Spot15)", "Spot15"),
    ("SCENE_SPOT16", "Death Mountain Trail (Spot16)", "Spot16"),
    ("SCENE_SPOT17", "Death Mountain Crater (Spot17)", "Spot17"),
    ("SCENE_SPOT18", "Goron City (Spot18)", "Spot18"),
    ("SCENE_SPOT20", "Lon Lon Ranch (Spot20)", "Spot20"),
    ("SCENE_GANON_TOU", "Ganon's Castle Exterior (Ganon Tou)", "Ganon Tou"),
    ("SCENE_TEST01", "Jungle Gym (Test01)", "Test01"),
    ("SCENE_BESITU", "Ganondorf Test Room (Besitu)", "Besitu"),
    ("SCENE_DEPTH_TEST", "Depth Test (Depth Test)", "Depth Test"),
    ("SCENE_SYOTES", "Stalfos Mini-Boss Room (Syotes)", "Syotes"),
    ("SCENE_SYOTES2", "Stalfos Boss ROom (Syotes2)", "Syotes2"),
    ("SCENE_SUTARU", "Sutaru (Sutaru)", "Sutaru"),
    ("SCENE_HAIRAL_NIWA2", "Castle Hedge Maze (Early) (Hairal Niwa2)", "Hairal Niwa2"),
    ("SCENE_SASATEST", "Sasatest (Sasatest)", "Sasatest"),
    ("SCENE_TESTROOM", "Treasure Chest Room (Testroom)", "Testroom"),
]

ootSceneIDToName = {
    "SCENE_YDAN": "ydan",
    "SCENE_DDAN": "ddan",
    "SCENE_BDAN": "bdan",
    "SCENE_BMORI1": "Bmori1",
    "SCENE_HIDAN": "HIDAN",
    "SCENE_MIZUSIN": "MIZUsin",
    "SCENE_JYASINZOU": "jyasinzou",
    "SCENE_HAKADAN": "HAKAdan",
    "SCENE_HAKADANCH": "HAKAdanCH",
    "SCENE_ICE_DOUKUTO": "ice_doukutu",
    "SCENE_GANON": "ganon",
    "SCENE_MEN": "men",
    "SCENE_GERUDOWAY": "gerudoway",
    "SCENE_GANONTIKA": "ganontika",
    "SCENE_GANON_SONOGO": "ganon_sonogo",
    "SCENE_GANONTIKA_SONOGO": "ganontikasonogo",
    "SCENE_TAKARAYA": "takaraya",
    "SCENE_YDAN_BOSS": "ydan_boss",
    "SCENE_DDAN_BOSS": "ddan_boss",
    "SCENE_BDAN_BOSS": "bdan_boss",
    "SCENE_MORIBOSSROOM": "moribossroom",
    "SCENE_FIRE_BS": "FIRE_bs",
    "SCENE_MIZUSIN_BS": "MIZUsin_bs",
    "SCENE_JYASINBOSS": "jyasinboss",
    "SCENE_HAKADAN_BS": "HAKAdan_bs",
    "SCENE_GANON_BOSS": "ganon_boss",
    "SCENE_GANON_FINAL": "ganon_final",
    "SCENE_ENTRA": "entra",
    "SCENE_ENTRA_N": "entra_n",
    "SCENE_ENRUI": "enrui",
    "SCENE_MARKET_ALLEY": "market_alley",
    "SCENE_MARKET_ALLEY_N": "market_alley_n",
    "SCENE_MARKET_DAY": "market_day",
    "SCENE_MARKET_NIGHT": "market_night",
    "SCENE_MARKET_RUINS": "market_ruins",
    "SCENE_SHRINE": "shrine",
    "SCENE_SHRINE_N": "shrine_n",
    "SCENE_SHRINE_R": "shrine_r",
    "SCENE_KOKIRI_HOME": "kokiri_home",
    "SCENE_KOKIRI_HOME3": "kokiri_home3",
    "SCENE_KOKIRI_HOME4": "kokiri_home4",
    "SCENE_KOKIRI_HOME5": "kokiri_home5",
    "SCENE_KAKARIKO": "kakariko",
    "SCENE_KAKARIKO3": "kakariko3",
    "SCENE_SHOP1": "shop1",
    "SCENE_KOKIRI_SHOP": "kokiri_shop",
    "SCENE_GOLON": "golon",
    "SCENE_ZOORA": "zoora",
    "SCENE_DRAG": "drag",
    "SCENE_ALLEY_SHOP": "alley_shop",
    "SCENE_NIGHT_SHOP": "night_shop",
    "SCENE_FACE_SHOP": "face_shop",
    "SCENE_LINK_HOME": "link_home",
    "SCENE_IMPA": "impa",
    "SCENE_MALON_STABLE": "malon_stable",
    "SCENE_LABO": "labo",
    "SCENE_HYLIA_LABO": "hylia_labo",
    "SCENE_TENT": "tent",
    "SCENE_HUT": "hut",
    "SCENE_DAIYOUSEI_IZUMI": "daiyousei_izumi",
    "SCENE_YOUSEI_IZUMI_TATE": "yousei_izumi_tate",
    "SCENE_YOUSEI_IZUMI_YOKO": "yousei_izumi_yoko",
    "SCENE_KAKUSIANA": "kakusiana",
    "SCENE_HAKAANA": "hakaana",
    "SCENE_HAKAANA2": "hakaana2",
    "SCENE_HAKAANA_OUKE": "hakaana_ouke",
    "SCENE_SYATEKIJYOU": "syatekijyou",
    "SCENE_TOKINOMA": "tokinoma",
    "SCENE_KENJYANOMA": "kenjyanoma",
    "SCENE_HAIRAL_NIWA": "hairal_niwa",
    "SCENE_HAIRAL_NIWA_N": "hairal_niwa_n",
    "SCENE_HIRAL_DEMO": "hiral_demo",
    "SCENE_HAKASITARELAY": "hakasitarelay",
    "SCENE_TURIBORI": "turibori",
    "SCENE_NAKANIWA": "nakaniwa",
    "SCENE_BOWLING": "bowling",
    "SCENE_SOUKO": "souko",
    "SCENE_MIHARIGOYA": "miharigoya",
    "SCENE_MAHOUYA": "mahouya",
    "SCENE_GANON_DEMO": "ganon_demo",
    "SCENE_KINSUTA": "kinsuta",
    "SCENE_SPOT00": "spot00",
    "SCENE_SPOT01": "spot01",
    "SCENE_SPOT02": "spot02",
    "SCENE_SPOT03": "spot03",
    "SCENE_SPOT04": "spot04",
    "SCENE_SPOT05": "spot05",
    "SCENE_SPOT06": "spot06",
    "SCENE_SPOT07": "spot07",
    "SCENE_SPOT08": "spot08",
    "SCENE_SPOT09": "spot09",
    "SCENE_SPOT10": "spot10",
    "SCENE_SPOT11": "spot11",
    "SCENE_SPOT12": "spot12",
    "SCENE_SPOT13": "spot13",
    "SCENE_SPOT15": "spot15",
    "SCENE_SPOT16": "spot16",
    "SCENE_SPOT17": "spot17",
    "SCENE_SPOT18": "spot18",
    "SCENE_SPOT20": "spot20",
    "SCENE_GANON_TOU": "ganon_tou",
    "SCENE_TEST01": "test01",
    "SCENE_BESITU": "besitu",
    "SCENE_DEPTH_TEST": "depth_test",
    "SCENE_SYOTES": "syotes",
    "SCENE_SYOTES2": "syotes2",
    "SCENE_SUTARU": "sutaru",
    "SCENE_HAIRAL_NIWA2": "hairal_niwa2",
    "SCENE_SASATEST": "sasatest",
    "SCENE_TESTROOM": "testroom",
}

ootEnumCamTransition = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "0x00", "0x00"),
    # ("0x0F", "0x0F", "0x0F"),
    # ("0xFF", "0xFF", "0xFF"),
]

# see curRoom.unk_03
ootEnumRoomBehaviour = [
    ("Custom", "Custom", "Custom"),
    ("0x00", "None", "None"),
    ("0x01", "Disable Sun Song Effect", "Disable Sun Song Effect"),
    ("0x02", "Disable Action Button Jumping", "Disable Action Button Jumping"),
    ("0x03", "(?) Disable Color Dither", "(?) Disable Color Dither"),
    ("0x04", "(?) Horse Camera Related", "(?) Horse Camera Related"),
    ("0x05", "(?) Nayru's Love Light Dim", "(?) Nayru's Love Light Dim"),
]

ootEnumExitIndex = [
    ("Custom", "Custom", "Custom"),
    ("Default", "Default", "Default"),
]

ootEnumSceneSetupPreset = [
    ("Custom", "Custom", "Custom"),
    ("All Scene Setups", "All Scene Setups", "All Scene Setups"),
    ("All Non-Cutscene Scene Setups", "All Non-Cutscene Scene Setups", "All Non-Cutscene Scene Setups"),
]

ootEnumCSWriteType = [
    ("Custom", "Custom", "Provide the name of a cutscene header variable"),
    ("Embedded", "Embedded", "Cutscene data is within scene header (deprecated)"),
    ("Object", "Object", "Reference to Blender object representing cutscene"),
]

ootEnumCSListType = [
    ("Textbox", "Textbox", "Textbox"),
    ("FX", "Scene Trans FX", "Scene Trans FX"),
    ("Lighting", "Lighting", "Lighting"),
    ("Time", "Time", "Time"),
    ("PlayBGM", "Play BGM", "Play BGM"),
    ("StopBGM", "Stop BGM", "Stop BGM"),
    ("FadeBGM", "Fade BGM", "Fade BGM"),
    ("Misc", "Misc", "Misc"),
    ("0x09", "Cmd 09", "Cmd 09"),
    ("Unk", "Unknown Data", "Unknown Data"),
]

ootEnumCSListTypeIcons = [
    "ALIGN_BOTTOM",
    "COLORSET_10_VEC",
    "LIGHT_SUN",
    "TIME",
    "PLAY",
    "SNAP_FACE",
    "IPO_EASE_IN_OUT",
    "OPTIONS",
    "EVENT_F9",
    "QUESTION",
]

ootEnumCSListTypeListC = {
    "Textbox": "CS_TEXT_LIST",
    "FX": "CS_SCENE_TRANS_FX",
    "Lighting": "CS_LIGHTING_LIST",
    "Time": "CS_TIME_LIST",
    "PlayBGM": "CS_PLAY_BGM_LIST",
    "StopBGM": "CS_STOP_BGM_LIST",
    "FadeBGM": "CS_FADE_BGM_LIST",
    "Misc": "CS_MISC_LIST",
    "0x09": "CS_CMD_09_LIST",
    "Unk": "CS_UNK_DATA_LIST",
}

ootEnumCSListTypeEntryC = {
    "Textbox": None,  # special case
    "FX": None,  # no list entries
    "Lighting": "CS_LIGHTING",
    "Time": "CS_TIME",
    "PlayBGM": "CS_PLAY_BGM",
    "StopBGM": "CS_STOP_BGM",
    "FadeBGM": "CS_FADE_BGM",
    "Misc": "CS_MISC",
    "0x09": "CS_CMD_09",
    "Unk": "CS_UNK_DATA",
}

ootEnumCSTextboxType = [("Text", "Text", "Text"), ("None", "None", "None"), ("LearnSong", "Learn Song", "Learn Song")]

ootEnumCSTextboxTypeIcons = ["FILE_TEXT", "HIDE_ON", "FILE_SOUND"]

ootEnumCSTextboxTypeEntryC = {
    "Text": "CS_TEXT_DISPLAY_TEXTBOX",
    "None": "CS_TEXT_NONE",
    "LearnSong": "CS_TEXT_LEARN_SONG",
}

ootEnumCSTransitionType = [
    ("1", "To White +", "Also plays whiteout sound for certain scenes/entrances"),
    ("2", "To Blue", "To Blue"),
    ("3", "From Red", "From Red"),
    ("4", "From Green", "From Green"),
    ("5", "From White", "From White"),
    ("6", "From Blue", "From Blue"),
    ("7", "To Red", "To Red"),
    ("8", "To Green", "To Green"),
    ("9", "Set Unk", "gSaveContext.unk_1410 = 1, works with scene xn 11/17"),
    ("10", "From Black", "From Black"),
    ("11", "To Black", "To Black"),
    ("12", "To Dim Unk", "Fade gSaveContext.unk_1410 255>100, works with scene xn 11/17"),
    ("13", "From Dim", "Alpha 100>255"),
]

ootDrawConfigNames = [
    "SDC_DEFAULT",
    "SDC_SPOT00",
    "SDC_SPOT01",
    "SDC_SPOT03",
    "SDC_SPOT04",
    "SDC_SPOT06",
    "SDC_SPOT07",
    "SDC_SPOT08",
    "SDC_SPOT09",
    "SDC_SPOT10",
    "SDC_SPOT11",
    "SDC_SPOT12",
    "SDC_SPOT13",
    "SDC_SPOT15",
    "SDC_SPOT16",
    "SDC_SPOT17",
    "SDC_SPOT18",
    "SDC_SPOT20",
    "SDC_HIDAN",
    "SDC_YDAN",
    "SDC_DDAN",
    "SDC_BDAN",
    "SDC_BMORI1",
    "SDC_MIZUSIN",
    "SDC_HAKADAN",
    "SDC_JYASINZOU",
    "SDC_GANONTIKA",
    "SDC_MEN",
    "SDC_YDAN_BOSS",
    "SDC_MIZUSIN_BS",
    "SDC_TOKINOMA",
    "SDC_KAKUSIANA",
    "SDC_KENJYANOMA",
    "SDC_GREAT_FAIRY_FOUNTAIN",
    "SDC_SYATEKIJYOU",
    "SDC_HAIRAL_NIWA",
    "SDC_GANON_CASTLE_EXTERIOR",
    "SDC_ICE_DOUKUTO",
    "SDC_GANON_FINAL",
    "SDC_FAIRY_FOUNTAIN",
    "SDC_GERUDOWAY",
    "SDC_BOWLING",
    "SDC_HAKAANA_OUKE",
    "SDC_HYLIA_LABO",
    "SDC_SOUKO",
    "SDC_MIHARIGOYA",
    "SDC_MAHOUYA",
    "SDC_CALM_WATER",
    "SDC_GRAVE_EXIT_LIGHT_SHINING",
    "SDC_BESITU",
    "SDC_TURIBORI",
    "SDC_GANON_SONOGO",
    "SDC_GANONTIKA_SONOGO",
]
