{
    "Amp": ActorPresetInfo(
        decomp_path="actors/amp",
        level="bbh",
        group="common0",
        animation=AnimInfo(
            address=134234164,
            behaviours={"Circling Amp": 318780296, "Homing Amp": 318780244},
            size=None,
            ignore_bone_count=True,
            dma=False,
            directory=None,
            names=["Moving"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=194, enum="MODEL_AMP")], geolayout=251658280, c_name=None, displaylist=None
        ),
        collision={},
    ),
    "Bird": ActorPresetInfo(
        decomp_path="actors/bird",
        level="castle_grounds",
        group="group10",
        animation=AnimInfo(
            address=83888616,
            behaviours={"Bird": 318788436, "End Birds 1": 318789212, "End Birds 2": 318789248},
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Flying", "Gliding"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=84, enum="MODEL_BIRDS")], geolayout=201326592, c_name=None, displaylist=None
        ),
        collision={},
    ),
    "Blargg": ActorPresetInfo(
        decomp_path="actors/blargg",
        level="lll",
        group="group2",
        animation=AnimInfo(
            address=83911020,
            behaviours={},
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Idle", "Bite"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=84, enum="MODEL_BLARGG")],
            geolayout=201327168,
            c_name="blargg_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Blue Coin Switch": ActorPresetInfo(
        decomp_path="actors/blue_coin_switch",
        level="bbh",
        group="common0",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=140, enum="MODEL_BLUE_COIN_SWITCH")],
            geolayout=251658240,
            c_name=None,
            displaylist=None,
        ),
        collision=CollisionInfo(address=134221464, c_name="blue_coin_switch_seg8_collision_08000E98"),
    ),
    "Blue Fish": ActorPresetInfo(
        decomp_path="actors/blue_fish",
        level="bbh",
        group="common1",
        animation=AnimInfo(
            address=50447024,
            behaviours=318774060,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Swimming", "Diving"],
        ),
        models={
            "Fish": ModelInfo(
                model_id=[ModelIDInfo(number=185, enum="MODEL_FISH")],
                geolayout=369101892,
                c_name=None,
                displaylist=None,
            ),
            "Fish (With Shadow)": ModelInfo(
                model_id=[ModelIDInfo(number=186, enum="MODEL_FISH_SHADOW")],
                geolayout=369101804,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Bobomb": ActorPresetInfo(
        decomp_path="actors/bobomb",
        level="bbh",
        group="common0",
        animation=AnimInfo(
            address=134363500,
            behaviours={"Bobomb": 318779764, "Bobomb Buddy": 318779868, "Bobomb Buddy (Opens Cannon)": 318779944},
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Walking", "Strugling"],
        ),
        models={
            "Bobomb": ModelInfo(
                model_id=[ModelIDInfo(number=188, enum="MODEL_BLACK_BOBOMB")],
                geolayout=251660216,
                c_name=None,
                displaylist=None,
            ),
            "Bobomb Buddy": ModelInfo(
                model_id=[ModelIDInfo(number=195, enum="MODEL_BOBOMB_BUDDY")],
                geolayout=251660532,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Bowser Bomb": ActorPresetInfo(
        decomp_path="actors/bomb",
        level="bowser_1",
        group="group12",
        animation={},
        models=ModelInfo(
            model_id=[
                ModelIDInfo(number=101, enum="MODEL_BOWSER_BOMB_CHILD_OBJ"),
                ModelIDInfo(number=179, enum="MODEL_BOWSER_BOMB"),
            ],
            geolayout=218106812,
            c_name="bowser_bomb_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Boo": ActorPresetInfo(
        decomp_path="actors/boo",
        level="bbh",
        group="group9",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=84, enum="MODEL_BOO")], geolayout=201327140, c_name="boo_geo", displaylist=None
        ),
        collision={},
    ),
    "Boo (Inside Castle)": ActorPresetInfo(
        decomp_path="actors/boo_castle",
        level="castle_inside",
        group="group15",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=101, enum="MODEL_BOO_CASTLE")],
            geolayout=218105264,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
    "Bookend": ActorPresetInfo(
        decomp_path="actors/book",
        level="bbh",
        group="group9",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=89, enum="MODEL_BOOKEND")],
            geolayout=201326784,
            c_name="bookend_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Bookend Part": ActorPresetInfo(
        decomp_path="actors/bookend",
        level="bbh",
        group="group9",
        animation=AnimInfo(
            address=83895616,
            behaviours=318787692,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Opening Mouth", "Bite", "Closed"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=88, enum="MODEL_BOOKEND_PART")],
            geolayout=201326592,
            c_name="bookend_part_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Metal Ball": ActorPresetInfo(
        decomp_path="actors/bowling_ball",
        level="bbh",
        group="common0",
        animation={},
        models={
            "Bowling Ball": ModelInfo(
                model_id=[ModelIDInfo(number=180, enum="MODEL_BOWLING_BALL")],
                geolayout=251659840,
                c_name=None,
                displaylist=None,
            ),
            "Trajectory Marker Ball": ModelInfo(
                model_id=[ModelIDInfo(number=225, enum="MODEL_TRAJECTORY_MARKER_BALL")],
                geolayout=251659884,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Bowser": ActorPresetInfo(
        decomp_path="actors/bowser",
        level="bowser_1",
        group="group12",
        animation=AnimInfo(
            address=101021664,
            behaviours=318773328,
            size=27,
            ignore_bone_count=True,
            dma=False,
            directory=None,
            names=[
                "Stand Up",
                "Stand Up (Unused)",
                "Shaking",
                "Grabbed",
                "Broken Animation (Unused)",
                "Fall Down",
                "Fire Breath",
                "Jump",
                "Jump Stop",
                "Jump Start",
                "Dance",
                "Fire Breath Up",
                "Idle",
                "Slow Gait",
                "Look Down Stop Walk",
                "Look Up Start Walk",
                "Flip Down",
                "Lay Down",
                "Run Start",
                "Run",
                "Run Stop",
                "Run Slip",
                "Fire Breath Quick",
                "Edge Move",
                "Edge Stop",
                "Flip",
                "Stand Up From Flip",
            ],
        ),
        models={
            "Bowser": ModelInfo(
                model_id=[ModelIDInfo(number=100, enum="MODEL_BOWSER")],
                geolayout=218106564,
                c_name=None,
                displaylist=None,
            ),
            "Bowser (No Shadow)": ModelInfo(
                model_id=[ModelIDInfo(number=105, enum="MODEL_BOWSER_NO_SHADOW")],
                geolayout=218106688,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Bowser Flame": ActorPresetInfo(
        decomp_path="actors/bowser_flame",
        level="bowser_1",
        group="group12",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=103, enum="MODEL_BOWSER_FLAMES")],
            geolayout=218103808,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
    "Bowser Key": ActorPresetInfo(
        decomp_path="actors/bowser_key",
        level="bbh",
        group="common1",
        animation=AnimInfo(
            address=50426576,
            behaviours={"Bowser Key": 318774196, "Bowser Key (Cutscene)": 318774228},
            size=2,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Unlock Door", "Course Exit"],
        ),
        models={
            "Bowser Key (Cutscene)": ModelInfo(
                model_id=[ModelIDInfo(number=200, enum="MODEL_BOWSER_KEY_CUTSCENE")],
                geolayout=369101488,
                c_name=None,
                displaylist=None,
            ),
            "Bowser Key": ModelInfo(
                model_id=[ModelIDInfo(number=204, enum="MODEL_BOWSER_KEY")],
                geolayout=369101444,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Breakable Box": ActorPresetInfo(
        decomp_path="actors/breakable_box",
        level="bbh",
        group="common0",
        animation={},
        models={
            "Breakable Box": ModelInfo(
                model_id=[ModelIDInfo(number=129, enum="MODEL_BREAKABLE_BOX")],
                geolayout=251659728,
                c_name=None,
                displaylist=None,
            ),
            "Breakable Box (Small)": ModelInfo(
                model_id=[ModelIDInfo(number=130, enum="MODEL_BREAKABLE_BOX_SMALL")],
                geolayout=251659792,
                c_name=None,
                displaylist=None,
            ),
        },
        collision=CollisionInfo(address=134294896, c_name="breakable_box_seg8_collision_08012D70"),
    ),
    "Bub": ActorPresetInfo(
        decomp_path="actors/bub",
        level="wdw",
        group="group13",
        animation=AnimInfo(
            address=100737876,
            behaviours=318775820,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Swimming"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=100, enum="MODEL_BUB")],
            geolayout=218104716,
            c_name="bub_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Bubba": ActorPresetInfo(
        decomp_path="actors/bubba",
        level="thi",
        group="group11",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=89, enum="MODEL_BUBBA")],
            geolayout=201326592,
            c_name="bubba_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Bubble": ActorPresetInfo(
        decomp_path="actors/bubble",
        level="bbh",
        group="group0",
        animation={},
        models={
            "Bubble": ModelInfo(
                model_id=[ModelIDInfo(number=168, enum="MODEL_BUBBLE")],
                geolayout=385875968,
                c_name=None,
                displaylist=None,
            ),
            "Bubble Marble": ModelInfo(
                model_id=[ModelIDInfo(number=170, enum="MODEL_PURPLE_MARBLE")],
                geolayout=385875996,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Bullet Bill": ActorPresetInfo(
        decomp_path="actors/bullet_bill",
        level="wf",
        group="group1",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=84, enum="MODEL_BULLET_BILL")],
            geolayout=201327204,
            c_name="bullet_bill_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Bully": ActorPresetInfo(
        decomp_path="actors/bully",
        level="lll",
        group="group2",
        animation=AnimInfo(
            address=83904268,
            behaviours={"Bully": 318781024, "Bully (With Minions)": 318781076, "Bully (Small)": 318780972},
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Patrol", "Chase", "Falling over (Unused)", "Knockback"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=86, enum="MODEL_BULLY")],
            geolayout=201326592,
            c_name="bully_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Burn Smoke": ActorPresetInfo(
        decomp_path="actors/burn_smoke",
        level="bbh",
        group="group0",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=148, enum="MODEL_BURN_SMOKE")],
            geolayout=385876100,
            c_name="burn_smoke_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Butterfly": ActorPresetInfo(
        decomp_path="actors/butterfly",
        level="bbh",
        group="common1",
        animation=AnimInfo(
            address=50353840,
            behaviours={"Butterfly": 318780348, "Triplet Butterfly": 318789016},
            size=2,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Flying", "Resting"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=187, enum="MODEL_BUTTERFLY")],
            geolayout=369098920,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
    "Cannon Barrel": ActorPresetInfo(
        decomp_path="actors/cannon_barrel",
        level="bbh",
        group="common0",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=127, enum="MODEL_CANNON_BARREL")],
            geolayout=251658688,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
    "Cannon Base": ActorPresetInfo(
        decomp_path="actors/cannon_base",
        level="bbh",
        group="common0",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=128, enum="MODEL_CANNON_BASE")],
            geolayout=251658664,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
    "Cannon Lid": ActorPresetInfo(
        decomp_path="actors/cannon_lid",
        level="bbh",
        group="common0",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=201, enum="MODEL_DL_CANNON_LID")],
            geolayout=None,
            c_name=None,
            displaylist=DisplaylistInfo(address=134236384, c_name="cannon_lid_seg8_dl_080048E0"),
        ),
        collision=CollisionInfo(address=134236496, c_name="cannon_lid_seg8_collision_08004950"),
    ),
    "Cap Switch": ActorPresetInfo(
        decomp_path="actors/capswitch",
        level="vcutm",
        group="group8",
        animation={},
        models={
            "Cap Switch": ModelInfo(
                model_id=[ModelIDInfo(number=85, enum="MODEL_CAP_SWITCH")],
                geolayout=201326664,
                c_name=None,
                displaylist=None,
            ),
            "Cap Switch (Exclamation)": ModelInfo(
                model_id=[ModelIDInfo(number=84, enum="MODEL_CAP_SWITCH_EXCLAMATION")],
                geolayout=None,
                c_name=None,
                displaylist=DisplaylistInfo(address=83897856, c_name="cap_switch_exclamation_seg5_dl_05002E00"),
            ),
            "Cap Switch (Base)": ModelInfo(
                model_id=[ModelIDInfo(number=86, enum="MODEL_CAP_SWITCH_BASE")],
                geolayout=None,
                c_name=None,
                displaylist=DisplaylistInfo(address=83898656, c_name="cap_switch_base_seg5_dl_05003120"),
            ),
        },
        collision={
            "Cap Switch (Base)": CollisionInfo(address=83899344, c_name="capswitch_collision_050033D0"),
            "Cap Switch (Top)": CollisionInfo(address=83899464, c_name="capswitch_collision_05003448"),
        },
    ),
    "Chain Ball": ActorPresetInfo(
        decomp_path="actors/chain_ball",
        level="bob",
        group="group14",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=101, enum="MODEL_METALLIC_BALL")],
            geolayout=218105296,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
    "Chain Chomp": ActorPresetInfo(
        decomp_path="actors/chain_chomp",
        level="bob",
        group="group14",
        animation=AnimInfo(
            address=100815224,
            behaviours=318785420,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Chomping"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=102, enum="MODEL_CHAIN_CHOMP")],
            geolayout=218105324,
            c_name="chain_chomp_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Haunted Chair": ActorPresetInfo(
        decomp_path="actors/chair",
        level="bbh",
        group="group9",
        animation=AnimInfo(
            address=83908484,
            behaviours=318787540,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Default Pose"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=86, enum="MODEL_HAUNTED_CHAIR")],
            geolayout=201326808,
            c_name="haunted_chair_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Checkerboard Platform": ActorPresetInfo(
        decomp_path="actors/checkerboard_platform",
        level="bbh",
        group="common0",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=202, enum="MODEL_CHECKERBOARD_PLATFORM")],
            geolayout=251659492,
            c_name=None,
            displaylist=None,
        ),
        collision=CollisionInfo(address=134272784, c_name="checkerboard_platform_seg8_collision_0800D710"),
    ),
    "Chilly Chief": ActorPresetInfo(
        decomp_path="actors/chilly_chief",
        level="ccm",
        group="group16",
        animation=AnimInfo(
            address=100678036,
            behaviours={"Chilly Chief (Small)": 318781128, "Chilly Chief (Big)": 318781184},
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Patrol", "Chase", "Falling over (Unused)", "Knockback"],
        ),
        models={
            "Chilly Chief (Small)": ModelInfo(
                model_id=[ModelIDInfo(number=100, enum="MODEL_CHILL_BULLY")],
                geolayout=100677460,
                c_name=None,
                displaylist=None,
            ),
            "Chilly Chief (Big)": ModelInfo(
                model_id=[ModelIDInfo(number=101, enum="MODEL_BIG_CHILL_BULLY")],
                geolayout=100677748,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Chuckya": ActorPresetInfo(
        decomp_path="actors/chuckya",
        level="bbh",
        group="common0",
        animation=AnimInfo(
            address=134266992,
            behaviours=318768424,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Grab Mario", "Holding Mario", "Being Held", "Throwing", "Moving", "Balancing/Idle (Unused)"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=223, enum="MODEL_CHUCKYA")], geolayout=251658712, c_name=None, displaylist=None
        ),
        collision={},
    ),
    "Clam Shell": ActorPresetInfo(
        decomp_path="actors/clam",
        level="jrb",
        group="group4",
        animation=AnimInfo(
            address=83892036,
            behaviours=318788672,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Close", "Open"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=88, enum="MODEL_CLAM_SHELL")],
            geolayout=201326592,
            c_name="clam_shell_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Coin": ActorPresetInfo(
        decomp_path="actors/coin",
        level="bbh",
        group="common1",
        animation={},
        models={
            "Yellow Coin": ModelInfo(
                model_id=[ModelIDInfo(number=116, enum="MODEL_YELLOW_COIN")],
                geolayout=369099068,
                c_name=None,
                displaylist=None,
            ),
            "Yellow Coin (No Shadow)": ModelInfo(
                model_id=[ModelIDInfo(number=117, enum="MODEL_YELLOW_COIN_NO_SHADOW")],
                geolayout=369099168,
                c_name=None,
                displaylist=None,
            ),
            "Blue Coin": ModelInfo(
                model_id=[ModelIDInfo(number=118, enum="MODEL_BLUE_COIN")],
                geolayout=369099264,
                c_name=None,
                displaylist=None,
            ),
            "Blue Coin (No Shadow)": ModelInfo(
                model_id=[ModelIDInfo(number=119, enum="MODEL_BLUE_COIN_NO_SHADOW")],
                geolayout=369099364,
                c_name=None,
                displaylist=None,
            ),
            "Red Coin": ModelInfo(
                model_id=[ModelIDInfo(number=215, enum="MODEL_RED_COIN")],
                geolayout=369099460,
                c_name=None,
                displaylist=None,
            ),
            "Red Coin (No Shadow)": ModelInfo(
                model_id=[ModelIDInfo(number=216, enum="MODEL_RED_COIN_NO_SHADOW")],
                geolayout=369099560,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Cyan Fish": ActorPresetInfo(
        decomp_path="actors/cyan_fish",
        level="wdw",
        group="group13",
        animation=AnimInfo(
            address=100721252,
            behaviours={},
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Swimming"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=103, enum="MODEL_CYAN_FISH")],
            geolayout=218104612,
            c_name="cyan_fish_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Dirt": ActorPresetInfo(
        decomp_path="actors/dirt",
        level="bbh",
        group="common1",
        animation={},
        models={
            "Dirt": ModelInfo(
                model_id=[ModelIDInfo(number=138, enum="MODEL_DIRT_ANIMATION")],
                geolayout=369102548,
                c_name=None,
                displaylist=None,
            ),
            "(Unused) Cartoon Start": ModelInfo(
                model_id=[ModelIDInfo(number=139, enum="MODEL_CARTOON_STAR")],
                geolayout=369102628,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Door": ActorPresetInfo(
        decomp_path="actors/door",
        level="bbh",
        group="common1",
        animation=AnimInfo(
            address=50419392,
            behaviours=318769932,
            size=None,
            ignore_bone_count=True,
            dma=False,
            directory=None,
            names=[
                "Closed",
                "Open and Close",
                "Open and Close (Slower?)",
                "Open and Close (Slower? Last 10 frames)",
                "Open and Close (Last 10 frames)",
            ],
        ),
        models={
            "Castle Door": ModelInfo(
                model_id=[
                    ModelIDInfo(number=38, enum="MODEL_CASTLE_GROUNDS_CASTLE_DOOR"),
                    ModelIDInfo(number=38, enum="MODEL_CASTLE_CASTLE_DOOR"),
                    ModelIDInfo(number=28, enum="MODEL_CASTLE_CASTLE_DOOR_UNUSED"),
                ],
                geolayout=369099688,
                c_name=None,
                displaylist=None,
            ),
            "Cabin Door": ModelInfo(
                model_id=[ModelIDInfo(number=39, enum="MODEL_CCM_CABIN_DOOR")],
                geolayout=369099836,
                c_name=None,
                displaylist=None,
            ),
            "Wooden Door": ModelInfo(
                model_id=[
                    ModelIDInfo(number=29, enum="MODEL_CASTLE_WOODEN_DOOR_UNUSED"),
                    ModelIDInfo(number=29, enum="MODEL_HMC_WOODEN_DOOR"),
                    ModelIDInfo(number=39, enum="MODEL_CASTLE_WOODEN_DOOR"),
                    ModelIDInfo(number=39, enum="MODEL_COURTYARD_WOODEN_DOOR"),
                ],
                geolayout=369099984,
                c_name=None,
                displaylist=None,
            ),
            "Wooden Door 2": ModelInfo(model_id=[], geolayout=369100132, c_name=None, displaylist=None),
            "Metal Door": ModelInfo(
                model_id=[
                    ModelIDInfo(number=31, enum="MODEL_HMC_METAL_DOOR"),
                    ModelIDInfo(number=41, enum="MODEL_CASTLE_METAL_DOOR"),
                    ModelIDInfo(number=41, enum="MODEL_CASTLE_GROUNDS_METAL_DOOR"),
                ],
                geolayout=369100312,
                c_name=None,
                displaylist=None,
            ),
            "Hazy Maze Door": ModelInfo(
                model_id=[ModelIDInfo(number=32, enum="MODEL_HMC_HAZY_MAZE_DOOR")],
                geolayout=369100428,
                c_name=None,
                displaylist=None,
            ),
            "Haunted Door": ModelInfo(
                model_id=[ModelIDInfo(number=29, enum="MODEL_BBH_HAUNTED_DOOR")],
                geolayout=369100576,
                c_name=None,
                displaylist=None,
            ),
            "Castle Door (0 Star)": ModelInfo(
                model_id=[ModelIDInfo(number=34, enum="MODEL_CASTLE_DOOR_0_STARS")],
                geolayout=369100724,
                c_name=None,
                displaylist=None,
            ),
            "Castle Door (1 Star)": ModelInfo(
                model_id=[ModelIDInfo(number=35, enum="MODEL_CASTLE_DOOR_1_STAR")],
                geolayout=369100904,
                c_name=None,
                displaylist=None,
            ),
            "Castle Door (3 Star)": ModelInfo(
                model_id=[ModelIDInfo(number=36, enum="MODEL_CASTLE_DOOR_3_STARS")],
                geolayout=369101084,
                c_name=None,
                displaylist=None,
            ),
            "Key Door": ModelInfo(
                model_id=[ModelIDInfo(number=37, enum="MODEL_CASTLE_KEY_DOOR")],
                geolayout=369101264,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Dorrie": ActorPresetInfo(
        decomp_path="actors/dorrie",
        level="hmc",
        group="group17",
        animation=AnimInfo(
            address=100726328,
            behaviours=318787472,
            size=3,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Idle", "Moving", "Lower and Raise Head"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=104, enum="MODEL_DORRIE")],
            geolayout=218104368,
            c_name="dorrie_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Exclamation Box": ActorPresetInfo(
        decomp_path="actors/exclamation_box",
        level="bbh",
        group="common0",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=137, enum="MODEL_EXCLAMATION_BOX")],
            geolayout=251659924,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
    "Exclamation Box Outline": ActorPresetInfo(
        decomp_path="actors/exclamation_box_outline",
        level="bbh",
        group="common0",
        animation={},
        models={
            "Exclamation Box Outline": ModelInfo(
                model_id=[ModelIDInfo(number=131, enum="MODEL_EXCLAMATION_BOX_OUTLINE")],
                geolayout=251660890,
                c_name=None,
                displaylist=None,
            ),
            "Exclamation Point": ModelInfo(
                model_id=[ModelIDInfo(number=132, enum="MODEL_EXCLAMATION_POINT")],
                geolayout=None,
                c_name=None,
                displaylist=DisplaylistInfo(address=134373128, c_name="exclamation_box_outline_seg8_dl_08025F08"),
            ),
        },
        collision=CollisionInfo(address=134373240, c_name="exclamation_box_outline_seg8_collision_08025F78"),
    ),
    "Explosion": ActorPresetInfo(
        decomp_path="actors/explosion",
        level="bbh",
        group="common1",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=205, enum="MODEL_EXPLOSION")],
            geolayout=369098816,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
    "Eyerok": ActorPresetInfo(
        decomp_path="actors/eyerok",
        level="ssl",
        group="group5",
        animation=AnimInfo(
            address=83957476,
            behaviours=318788276,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Recovering", "Death", "Idle", "Attacked", "Open", "Show Eye", "Sleep", "Close"],
        ),
        models={
            "Eyerok Left Hand": ModelInfo(
                model_id=[ModelIDInfo(number=88, enum="MODEL_EYEROK_LEFT_HAND")],
                geolayout=201328040,
                c_name=None,
                displaylist=None,
            ),
            "Eyerok Right Hand": ModelInfo(
                model_id=[ModelIDInfo(number=89, enum="MODEL_EYEROK_RIGHT_HAND")],
                geolayout=201328100,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Flame": ActorPresetInfo(
        decomp_path="actors/flame",
        level="bbh",
        group="common1",
        animation={},
        models={
            "Red Flame (With Shadow)": ModelInfo(
                model_id=[ModelIDInfo(number=203, enum="MODEL_RED_FLAME_SHADOW")],
                geolayout=369101584,
                c_name=None,
                displaylist=None,
            ),
            "Red Flame": ModelInfo(
                model_id=[ModelIDInfo(number=144, enum="MODEL_RED_FLAME")],
                geolayout=369101612,
                c_name=None,
                displaylist=None,
            ),
            "Blue Flame": ModelInfo(
                model_id=[ModelIDInfo(number=145, enum="MODEL_BLUE_FLAME")],
                geolayout=369101708,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Fly Guy": ActorPresetInfo(
        decomp_path="actors/flyguy",
        level="bbh",
        group="common0",
        animation=AnimInfo(
            address=134290020,
            behaviours=318785244,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Flying"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=220, enum="MODEL_FLYGUY")], geolayout=251659544, c_name=None, displaylist=None
        ),
        collision={},
    ),
    "Fwoosh": ActorPresetInfo(
        decomp_path="actors/fwoosh",
        level="ttm",
        group="group6",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=87, enum="MODEL_FWOOSH")],
            geolayout=201327468,
            c_name="fwoosh_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Goomba": ActorPresetInfo(
        decomp_path="actors/goomba",
        level="bbh",
        group="common0",
        animation=AnimInfo(
            address=134339148,
            behaviours=318785324,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Walking"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=192, enum="MODEL_GOOMBA")], geolayout=251660004, c_name=None, displaylist=None
        ),
        collision={},
    ),
    "Haunted Cage": ActorPresetInfo(
        decomp_path="actors/haunted_cage",
        level="bbh",
        group="group9",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=90, enum="MODEL_HAUNTED_CAGE")],
            geolayout=201327220,
            c_name="haunted_cage_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Heart": ActorPresetInfo(
        decomp_path="actors/heart",
        level="bbh",
        group="common0",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=120, enum="MODEL_HEART")], geolayout=251659516, c_name=None, displaylist=None
        ),
        collision={},
    ),
    "Heave-Ho": ActorPresetInfo(
        decomp_path="actors/heave_ho",
        level="wf",
        group="group1",
        animation=AnimInfo(
            address=83972940,
            behaviours=318772552,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Moving", "Throwing", "Stop"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=89, enum="MODEL_HEAVE_HO")],
            geolayout=201327244,
            c_name="heave_ho_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Hoot": ActorPresetInfo(
        decomp_path="actors/hoot",
        level="wf",
        group="group1",
        animation=AnimInfo(
            address=83908456,
            behaviours=318780396,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Flying", "Flying Fast"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=86, enum="MODEL_HOOT")],
            geolayout=201326616,
            c_name="hoot_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Bowser Impact Ring": ActorPresetInfo(
        decomp_path="actors/impact_ring",
        level="bowser_1",
        group="group12",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=104, enum="MODEL_BOWSER_WAVE")],
            geolayout=218103952,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
    "Bowser Impact Smoke": ActorPresetInfo(
        decomp_path="actors/impact_smoke",
        level="bowser_1",
        group="group12",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=102, enum="MODEL_BOWSER_SMOKE")],
            geolayout=218106876,
            c_name="bowser_impact_smoke_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "King Bobomb": ActorPresetInfo(
        decomp_path="actors/bobomb",
        level="bob",
        group="group3",
        animation=AnimInfo(
            address=83951152,
            behaviours=318767604,
            size=12,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=[
                "Grab Mario",
                "Holding Mario",
                "Hit Ground",
                "Unkwnown (Unused)",
                "Stomp",
                "Idle",
                "Being Held",
                "Landing",
                "Jump",
                "Throw Mario",
                "Stand Up",
                "Walking",
            ],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=86, enum="MODEL_KING_BOBOMB")],
            geolayout=201326592,
            c_name="king_bobomb_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Klepto": ActorPresetInfo(
        decomp_path="actors/klepto",
        level="ssl",
        group="group5",
        animation=AnimInfo(
            address=83922172,
            behaviours=318788368,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=[
                "Dive",
                "Struck By Mario",
                "Dive at Mario",
                "Dive at Mario 2",
                "Dive at Mario 3",
                "Dive at Mario 4",
                "Dive Flap",
                "Dive Flap 2",
            ],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=87, enum="MODEL_KLEPTO")],
            geolayout=201326592,
            c_name="klepto_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Koopa": ActorPresetInfo(
        decomp_path="actors/koopa",
        level="bob",
        group="group14",
        animation=AnimInfo(
            address=100733796,
            behaviours=318784896,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=[
                "Falling Over (Unused Shelled Act 3)",
                "Run Away",
                "Laying (Unshelled)",
                "Running",
                "Run (Unused)",
                "Laying (Shelled)",
                "Stand Up",
                "Stopped",
                "Wake Up (Unused)",
                "Walk",
                "Walk Stop",
                "Walk Start",
                "Jump",
                "Land",
            ],
        ),
        models={
            "Koopa (Without Shell)": ModelInfo(
                model_id=[ModelIDInfo(number=191, enum="MODEL_KOOPA_WITHOUT_SHELL")],
                geolayout=218104016,
                c_name=None,
                displaylist=None,
            ),
            "Koopa (With Shell)": ModelInfo(
                model_id=[ModelIDInfo(number=104, enum="MODEL_KOOPA_WITH_SHELL")],
                geolayout=218104340,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Koopa Flag": ActorPresetInfo(
        decomp_path="actors/koopa_flag",
        level="bob",
        group="group14",
        animation=AnimInfo(
            address=100667432,
            behaviours=318785016,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Waving"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=106, enum="MODEL_KOOPA_FLAG")],
            geolayout=218103808,
            c_name="koopa_flag_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Koopa Shell": ActorPresetInfo(
        decomp_path="actors/koopa_shell",
        level="bbh",
        group="common0",
        animation={},
        models={
            "Koopa Shell": ModelInfo(
                model_id=[ModelIDInfo(number=190, enum="MODEL_KOOPA_SHELL")],
                geolayout=251660976,
                c_name=None,
                displaylist=None,
            ),
            "(Unused) Koopa Shell 1": ModelInfo(model_id=[], geolayout=251661020, c_name=None, displaylist=None),
            "(Unused) Koopa Shell 2": ModelInfo(model_id=[], geolayout=251661064, c_name=None, displaylist=None),
        },
        collision={},
    ),
    "Lakitu (Cameraman)": ActorPresetInfo(
        decomp_path="actors/lakitu_cameraman",
        level="castle_inside",
        group="group15",
        animation=AnimInfo(
            address=100686072,
            behaviours={"Lakitu (Beginning)": 318789136, "Lakitu (Cameraman)": 318785876},
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Flying"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=102, enum="MODEL_LAKITU")], geolayout=218103808, c_name=None, displaylist=None
        ),
        collision={},
    ),
    "Lakitu (Enemy)": ActorPresetInfo(
        decomp_path="actors/lakitu_enemy",
        level="thi",
        group="group11",
        animation=AnimInfo(
            address=83969236,
            behaviours=318785816,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Flying", "No Spiny", "Throw Spiny", "Hold Spiny"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=84, enum="MODEL_ENEMY_LAKITU")],
            geolayout=201327036,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
    "Leaves": ActorPresetInfo(
        decomp_path="actors/leaves",
        level="bbh",
        group="common1",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=162, enum="MODEL_LEAVES")], geolayout=369101964, c_name=None, displaylist=None
        ),
        collision={},
    ),
    "Mad Piano": ActorPresetInfo(
        decomp_path="actors/mad_piano",
        level="bbh",
        group="group9",
        animation=AnimInfo(
            address=83925780,
            behaviours=318787620,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Sleeping", "Chomping"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=87, enum="MODEL_MAD_PIANO")],
            geolayout=201327028,
            c_name="mad_piano_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Manta Ray": ActorPresetInfo(
        decomp_path="actors/manta",
        level="jrb",
        group="group4",
        animation=AnimInfo(
            address=83922612,
            behaviours=318784368,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Swimming"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=84, enum="MODEL_MANTA_RAY")], geolayout=83922196, c_name=None, displaylist=None
        ),
        collision={},
    ),
    "Mario": ActorPresetInfo(
        decomp_path="actors/mario",
        level="bbh",
        group="group0",
        animation=AnimInfo(
            address=5160960,
            behaviours={},
            size=None,
            ignore_bone_count=False,
            dma=True,
            directory="assets/anims",
            names=[
                "Slow ledge climb up",
                "Fall over backwards",
                "Backward air kb",
                "Dying on back",
                "Backflip",
                "Climbing up pole",
                "Grab pole short",
                "Grab pole swing part 1",
                "Grab pole swing part 2",
                "Handstand idle",
                "Handstand jump",
                "Start handstand",
                "Return from handstand",
                "Idle on pole",
                "A pose",
                "Skid on ground",
                "Stop skid",
                "Crouch from fast longjump",
                "Crouch from a slow longjump",
                "Fast longjump",
                "Slow longjump",
                "Airborne on stomach",
                "Walk with light object",
                "Run with light object",
                "Slow walk with light object",
                "Shivering and warming hands",
                "Shivering return to idle ",
                "Shivering",
                "Climb down on ledge",
                "Waving (Credits)",
                "Look up (Credits)",
                "Return from look up (Credits)",
                "Raising hand (Credits)",
                "Lowering hand (Credits)",
                "Taking off cap (Credits)",
                "Start walking and look up (Credits)",
                "Look back then run (Credits)",
                "Final Bowser - Raise hand and spin",
                "Final Bowser - Wing cap take off",
                "Peach sign (Credits)",
                "Stand up from lava boost",
                "Fire/Lava burn",
                "Wing cap flying",
                "Hang on owl",
                "Land on stomach",
                "Air forward kb",
                "Dying on stomach",
                "Suffocating",
                "Coughing",
                "Throw catch key",
                "Dying fall over",
                "Idle on ledge",
                "Fast ledge grab",
                "Hang on ceiling",
                "Put cap on",
                "Take cap off then on",
                "Quickly put cap on",
                "Head stuck in ground",
                "Ground pound landing",
                "Triple jump ground-pound",
                "Start ground-pound",
                "Ground-pound",
                "Bottom stuck in ground",
                "Idle with light object",
                "Jump land with light object",
                "Jump with light object",
                "Fall land with light object",
                "Fall with light object",
                "Fall from sliding with light object",
                "Sliding on bottom with light object",
                "Stand up from sliding with light object",
                "Riding shell",
                "Walking",
                "Forward flip",
                "Jump riding shell",
                "Land from double jump",
                "Double jump fall",
                "Single jump",
                "Land from single jump",
                "Air kick",
                "Double jump rise",
                "Start forward spinning",
                "Throw light object",
                "Fall from slide kick",
                "Bend kness riding shell",
                "Legs stuck in ground",
                "General fall",
                "General land",
                "Being grabbed",
                "Grab heavy object",
                "Slow land from dive",
                "Fly from cannon",
                "Moving right while hanging",
                "Moving left while hanging",
                "Missing cap",
                "Pull door walk in",
                "Push door walk in",
                "Unlock door",
                "Start reach pocket",
                "Reach pocket",
                "Stop reach pocket",
                "Ground throw",
                "Ground kick",
                "First punch",
                "Second punch",
                "First punch fast",
                "Second punch fast",
                "Pick up light object",
                "Pushing",
                "Start riding shell",
                "Place light object",
                "Forward spinning",
                "Backward spinning",
                "Breakdance",
                "Running",
                "Running (unused)",
                "Soft back kb",
                "Soft front kb",
                "Dying in quicksand",
                "Idle in quicksand",
                "Move in quicksand",
                "Electrocution",
                "Shocked",
                "Backward kb",
                "Forward kb",
                "Idle heavy object",
                "Stand against wall",
                "Side step left",
                "Side step right",
                "Start sleep idle",
                "Start sleep scratch",
                "Start sleep yawn",
                "Start sleep sitting",
                "Sleep idle",
                "Sleep start laying",
                "Sleep laying",
                "Dive",
                "Slide dive",
                "Ground bonk",
                "Stop slide light object",
                "Slide kick",
                "Crouch from slide kick",
                "Slide motionless",
                "Stop slide",
                "Fall from slide",
                "Slide",
                "Tiptoe",
                "Twirl land",
                "Twirl",
                "Start twirl",
                "Stop crouching",
                "Start crouching",
                "Crouching",
                "Crawling",
                "Stop crawling",
                "Start crawling",
                "Summon star",
                "Return star approach door",
                "Backwards water kb",
                "Swim with object part 1",
                "Swim with object part 2",
                "Flutter kick with object",
                "Action end with object in water",
                "Stop holding object in water",
                "Holding object in water",
                "Drowning part 1",
                "Drowning part 2",
                "Dying in water",
                "Forward kb in water",
                "Falling from water",
                "Swimming part 1",
                "Swimming part 2",
                "Flutter kick",
                "Action end in water",
                "Pick up object in water",
                "Grab object in water part 2",
                "Grab object in water part 1",
                "Throw object in water",
                "Idle in water",
                "Star dance in water",
                "Return from in water star dance",
                "Grab bowser",
                "Swing bowser",
                "Release bowser",
                "Holding bowser",
                "Heavy throw",
                "Walk panting",
                "Walk with heavy object",
                "Turning part 1",
                "Turning part 2",
                "Side flip land",
                "Side flip",
                "Triple jump land",
                "Triple jump",
                "First person",
                "Idle head left",
                "Idle head right",
                "Idle head center",
                "Handstand left",
                "Handstand right",
                "Wake up from sleeping",
                "Wake up from laying",
                "Start tiptoeing",
                "Slide jump",
                "Start wallkick",
                "Star dance",
                "Return from star dance",
                "Forwards spinning flip",
                "Triple jump fly",
            ],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=1, enum="MODEL_MARIO")],
            geolayout=385887700,
            c_name="mario_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Mario's Cap": ActorPresetInfo(
        decomp_path="actors/mario_cap",
        level="bbh",
        group="common1",
        animation={},
        models={
            "Mario's Cap": ModelInfo(
                model_id=[ModelIDInfo(number=136, enum="MODEL_MARIOS_CAP")],
                geolayout=369101988,
                c_name=None,
                displaylist=None,
            ),
            "Mario's Metal Cap": ModelInfo(
                model_id=[ModelIDInfo(number=134, enum="MODEL_MARIOS_METAL_CAP")],
                geolayout=369102064,
                c_name=None,
                displaylist=None,
            ),
            "Mario's Wing Cap": ModelInfo(
                model_id=[ModelIDInfo(number=135, enum="MODEL_MARIOS_WING_CAP")],
                geolayout=369102140,
                c_name=None,
                displaylist=None,
            ),
            "Mario's Winged Metal Cap": ModelInfo(
                model_id=[ModelIDInfo(number=133, enum="MODEL_MARIOS_WINGED_METAL_CAP")],
                geolayout=369102248,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Metal Box": ActorPresetInfo(
        decomp_path="actors/metal_box",
        level="bbh",
        group="common0",
        animation={},
        models={
            "Metal Box": ModelInfo(
                model_id=[ModelIDInfo(number=217, enum="MODEL_METAL_BOX")],
                geolayout=251660848,
                c_name=None,
                displaylist=None,
            ),
            "Metal Box (DL)": ModelInfo(
                model_id=[ModelIDInfo(number=218, enum="MODEL_METAL_BOX_DL")],
                geolayout=None,
                c_name=None,
                displaylist=DisplaylistInfo(address=134368184, c_name="metal_box_dl"),
            ),
        },
        collision=CollisionInfo(address=134368296, c_name="metal_box_seg8_collision_08024C28"),
    ),
    "Mips": ActorPresetInfo(
        decomp_path="actors/mips",
        level="castle_inside",
        group="group15",
        animation=AnimInfo(
            address=100751140,
            behaviours=318784764,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Idle", "Hopping", "Thrown", "Thrown (Unused)", "Held"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=100, enum="MODEL_MIPS")],
            geolayout=218104904,
            c_name="mips_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Mist": ActorPresetInfo(
        decomp_path="actors/mist",
        level="bbh",
        group="common1",
        animation={},
        models={
            "Mist": ModelInfo(
                model_id=[ModelIDInfo(number=142, enum="MODEL_MIST")],
                geolayout=369098752,
                c_name=None,
                displaylist=None,
            ),
            "White Puff": ModelInfo(
                model_id=[ModelIDInfo(number=224, enum="MODEL_WHITE_PUFF")],
                geolayout=369098784,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Moneybag": ActorPresetInfo(
        decomp_path="actors/moneybag",
        level="ccm",
        group="group16",
        animation=AnimInfo(
            address=100687452,
            behaviours=318781856,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Idle", "Prepare", "Jump", "Land", "Walk"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=102, enum="MODEL_MONEYBAG")],
            geolayout=218104048,
            c_name="moneybag_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Monty Mole": ActorPresetInfo(
        decomp_path="actors/monty_mole",
        level="ttm",
        group="group6",
        animation=AnimInfo(
            address=83915336,
            behaviours=318786048,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=[
                "Jump Into Hole",
                "Rise",
                "Get Rock",
                "Begin Jump Into Hole",
                "Jump Out Of Hole Down",
                "Unused 5",
                "Unused 6",
                "Unused 7",
                "Throw Rock",
                "Jump Out Of Hole Up",
            ],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=85, enum="MODEL_MONTY_MOLE")],
            geolayout=201326592,
            c_name="monty_mole_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Montey Mole Hole": ActorPresetInfo(
        decomp_path="actors/monty_mole_hole",
        level="ttm",
        group="group6",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=84, enum="MODEL_DL_MONTY_MOLE_HOLE")],
            geolayout=None,
            c_name=None,
            displaylist=DisplaylistInfo(address=83888192, c_name="monty_mole_hole_seg5_dl_05000840"),
        ),
        collision={},
    ),
    "Mr. I Eyeball": ActorPresetInfo(
        decomp_path="actors/mr_i_eyeball",
        level="ccm",
        group="group16",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=103, enum="MODEL_MR_I")], geolayout=218103808, c_name=None, displaylist=None
        ),
        collision={},
    ),
    "Mr. I Iris": ActorPresetInfo(
        decomp_path="actors/mr_i_iris",
        level="ccm",
        group="group16",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=102, enum="MODEL_MR_I_IRIS")],
            geolayout=218103836,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
    "Mushroom 1up": ActorPresetInfo(
        decomp_path="actors/mushroom_1up",
        level="bbh",
        group="common1",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=212, enum="MODEL_1UP")], geolayout=369102468, c_name=None, displaylist=None
        ),
        collision={},
    ),
    "Orange Numbers": ActorPresetInfo(
        decomp_path="actors/number",
        level="bbh",
        group="common1",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=219, enum="MODEL_NUMBER")], geolayout=369102356, c_name=None, displaylist=None
        ),
        collision={},
    ),
    "Peach": ActorPresetInfo(
        decomp_path="actors/peach",
        level="castle_grounds",
        group="group10",
        animation=AnimInfo(
            address=84002052,
            behaviours={"Peach (Beginning)": 318789176, "Peach (End)": 318770860},
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=[
                "Listen Everybody",
                "Turning Away",
                "Walking away",
                "Walking away 2",
                "Descend",
                "Descend And Look Down",
                "Look Up And Open Eyes",
                "Mario",
                "Power Of The Stars",
                "Thanks To You",
                "Kiss",
                "Waving",
            ],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=222, enum="MODEL_PEACH")],
            geolayout=201327632,
            c_name="peach_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Pebble": ActorPresetInfo(
        decomp_path="actors/pebble",
        level="bbh",
        group="common1",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=161, enum="MODEL_PEBBLE")],
            geolayout=None,
            c_name=None,
            displaylist=DisplaylistInfo(address=50449152, c_name="pebble_seg3_dl_0301CB00"),
        ),
        collision={},
    ),
    "Penguin": ActorPresetInfo(
        decomp_path="actors/penguin",
        level="ccm",
        group="group7",
        animation=AnimInfo(
            address=83921780,
            behaviours={
                "Penguin (Tuxies Mother)": 318775432,
                "Penguin (Small)": 318775528,
                "Penguin (SML)": 318778968,
                "Racing Penguin": 318788480,
            },
            size=5,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Walk", "Dive Slide", "Stand Up", "Idle", "Walk"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=87, enum="MODEL_PENGUIN")],
            geolayout=201326852,
            c_name="penguin_geo",
            displaylist=None,
        ),
        collision=CollisionInfo(address=83921800, c_name="penguin_seg5_collision_05008B88"),
    ),
    "Piranha Plant": ActorPresetInfo(
        decomp_path="actors/piranha_plant",
        level="bob",
        group="group14",
        animation=AnimInfo(
            address=100778780,
            behaviours={"Fire Piranha Plant": 318787872, "Piranha Plant": 318775228},
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=[
                "Bite",
                "Sleeping? (Unused)",
                "Falling over",
                "Bite (Unused)",
                "Grow",
                "Attacked",
                "Stop Bitting",
                "Sleeping (Unused)",
                "Sleeping",
                "Bite (Duplicate)",
            ],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=100, enum="MODEL_PIRANHA_PLANT")],
            geolayout=218104664,
            c_name="piranha_plant_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Pokey": ActorPresetInfo(
        decomp_path="actors/pokey",
        level="ssl",
        group="group5",
        animation={},
        models={
            "Pokey Head": ModelInfo(
                model_id=[ModelIDInfo(number=84, enum="MODEL_POKEY_HEAD")],
                geolayout=201328144,
                c_name=None,
                displaylist=None,
            ),
            "Pokey Body Part": ModelInfo(
                model_id=[ModelIDInfo(number=85, enum="MODEL_POKEY_BODY_PART")],
                geolayout=201328196,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Wooden Post": ActorPresetInfo(
        decomp_path="actors/poundable_pole",
        level="bob",
        group="group14",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=107, enum="MODEL_WOODEN_POST")],
            geolayout=218103992,
            c_name="wooden_post_geo",
            displaylist=None,
        ),
        collision=CollisionInfo(address=100672656, c_name="poundable_pole_collision_06002490"),
    ),
    "Power Meter": ActorPresetInfo(
        decomp_path="actors/power_meter",
        level="bbh",
        group="common1",
        animation={},
        models={
            "Power Meter (Base)": ModelInfo(
                model_id=[],
                geolayout=None,
                c_name=None,
                displaylist=DisplaylistInfo(address=50500736, c_name="dl_power_meter_base"),
            ),
            "Power Meter (Health)": ModelInfo(
                model_id=[],
                geolayout=None,
                c_name=None,
                displaylist=DisplaylistInfo(address=50500976, c_name="dl_power_meter_health_segments_begin"),
            ),
        },
        collision={},
    ),
    "Purple Switch": ActorPresetInfo(
        decomp_path="actors/purple_switch",
        level="bbh",
        group="common0",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=207, enum="MODEL_PURPLE_SWITCH")],
            geolayout=251659468,
            c_name=None,
            displaylist=None,
        ),
        collision=CollisionInfo(address=134268840, c_name="purple_switch_seg8_collision_0800C7A8"),
    ),
    "Sand": ActorPresetInfo(
        decomp_path="actors/sand",
        level="bbh",
        group="common1",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=159, enum="MODEL_SAND_DUST")],
            geolayout=None,
            c_name=None,
            displaylist=DisplaylistInfo(address=50511056, c_name="sand_seg3_dl_0302BCD0"),
        ),
        collision={},
    ),
    "Scuttlebug": ActorPresetInfo(
        decomp_path="actors/scuttlebug",
        level="hmc",
        group="group17",
        animation=AnimInfo(
            address=100749412,
            behaviours=318778204,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Walking"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=101, enum="MODEL_SCUTTLEBUG")],
            geolayout=218104724,
            c_name="scuttlebug_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Seaweed": ActorPresetInfo(
        decomp_path="actors/seaweed",
        level="wdw",
        group="group13",
        animation=AnimInfo(
            address=100705492,
            behaviours=318779700,
            size=1,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Wave"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=193, enum="MODEL_SEAWEED")],
            geolayout=218104452,
            c_name="seaweed_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Skeeter": ActorPresetInfo(
        decomp_path="actors/skeeter",
        level="wdw",
        group="group13",
        animation=AnimInfo(
            address=100695520,
            behaviours=318788712,
            size=4,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Water Lunge", "Water Idle", "Walk", "Idle"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=105, enum="MODEL_SKEETER")],
            geolayout=218103808,
            c_name="skeeter_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "(Beta) Boo Key": ActorPresetInfo(
        decomp_path="actors/small_key",
        level="bbh",
        group="group9",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=85, enum="MODEL_BETA_BOO_KEY")],
            geolayout=201326984,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
    "(Unused) Smoke": ActorPresetInfo(
        decomp_path="actors/smoke",
        level="ttm",
        group="group6",
        animation={},
        models=ModelInfo(
            model_id=[],
            geolayout=None,
            c_name=None,
            displaylist=DisplaylistInfo(address=83917560, c_name="smoke_seg5_dl_05007AF8"),
        ),
        collision={},
    ),
    "Mr. Blizzard": ActorPresetInfo(
        decomp_path="actors/snowman",
        level="ccm",
        group="group7",
        animation=AnimInfo(
            address=83939608,
            behaviours={"Mr. Blizzard": 318787004},
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Spawn Snowball", "Throw Snowball"],
        ),
        models={
            "Mr. Blizzard": ModelInfo(
                model_id=[ModelIDInfo(number=86, enum="MODEL_MR_BLIZZARD")],
                geolayout=201327432,
                c_name=None,
                displaylist=None,
            ),
            "Mr. Blizzard (Hidden)": ModelInfo(
                model_id=[ModelIDInfo(number=85, enum="MODEL_MR_BLIZZARD_HIDDEN")],
                geolayout=201327132,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Snufit": ActorPresetInfo(
        decomp_path="actors/snufit",
        level="hmc",
        group="group17",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=206, enum="MODEL_SNUFIT")],
            geolayout=218104224,
            c_name="snufit_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Sparkle": ActorPresetInfo(
        decomp_path="actors/sparkle",
        level="bbh",
        group="group0",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=149, enum="MODEL_SPARKLES")],
            geolayout=385876412,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
    "Sparkle Animation": ActorPresetInfo(
        decomp_path="actors/sparkle_animation",
        level="bbh",
        group="group0",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=143, enum="MODEL_SPARKLES_ANIMATION")],
            geolayout=385876612,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
    "Spindrift": ActorPresetInfo(
        decomp_path="actors/spindrift",
        level="ccm",
        group="group7",
        animation=AnimInfo(
            address=83897704,
            behaviours=318771892,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Flying"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=84, enum="MODEL_SPINDRIFT")],
            geolayout=201326592,
            c_name="spindrift_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Spiny": ActorPresetInfo(
        decomp_path="actors/spiny",
        level="thi",
        group="group11",
        animation=AnimInfo(
            address=83979948,
            behaviours={"Spiny": 318785992},
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Walk"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=86, enum="MODEL_SPINY")],
            geolayout=201327400,
            c_name="spiny_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Spiny Egg": ActorPresetInfo(
        decomp_path="actors/spiny_egg",
        level="thi",
        group="group11",
        animation=AnimInfo(
            address=83974116,
            behaviours={},
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Default"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=85, enum="MODEL_SPINY_BALL")],
            geolayout=201327248,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
    "Springboard": ActorPresetInfo(
        decomp_path="actors/springboard",
        level="vcutm",
        group="group8",
        animation={},
        models={
            "Springboard Top": ModelInfo(
                model_id=[ModelIDInfo(number=181, enum="MODEL_TRAMPOLINE")],
                geolayout=201326592,
                c_name=None,
                displaylist=None,
            ),
            "Springboard Middle": ModelInfo(
                model_id=[ModelIDInfo(number=182, enum="MODEL_TRAMPOLINE_CENTER")],
                geolayout=201326616,
                c_name=None,
                displaylist=None,
            ),
            "Springboard Bottom": ModelInfo(
                model_id=[ModelIDInfo(number=183, enum="MODEL_TRAMPOLINE_BASE")],
                geolayout=201326640,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Star": ActorPresetInfo(
        decomp_path="actors/star",
        level="bbh",
        group="common1",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=122, enum="MODEL_STAR")], geolayout=369102496, c_name=None, displaylist=None
        ),
        collision={},
    ),
    "Small Water Splash": ActorPresetInfo(
        decomp_path="actors/stomp_smoke",
        level="bbh",
        group="group0",
        animation={},
        models={
            "Small Water Splash": ModelInfo(
                model_id=[ModelIDInfo(number=165, enum="MODEL_SMALL_WATER_SPLASH")],
                geolayout=385876124,
                c_name=None,
                displaylist=None,
            ),
            "(Unused) Small Water Splash": ModelInfo(model_id=[], geolayout=385876192, c_name=None, displaylist=None),
        },
        collision={},
    ),
    "Sushi Shark": ActorPresetInfo(
        decomp_path="actors/sushi",
        level="jrb",
        group="group4",
        animation=AnimInfo(
            address=83930708,
            behaviours=318776120,
            size=1,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Swimming", "Diving"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=86, enum="MODEL_SUSHI")], geolayout=201326696, c_name=None, displaylist=None
        ),
        collision={},
    ),
    "Swoop": ActorPresetInfo(
        decomp_path="actors/swoop",
        level="hmc",
        group="group17",
        animation=AnimInfo(
            address=100692176,
            behaviours=318785176,
            size=2,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Idle", "Move"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=100, enum="MODEL_SWOOP")],
            geolayout=218104028,
            c_name="swoop_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Test Plataform": ActorPresetInfo(
        decomp_path="actors/test_plataform",
        level="bbh",
        group="common0",
        animation={},
        models={},
        collision=CollisionInfo(address=134374136, c_name="unknown_seg8_collision_080262F8"),
    ),
    "Thwomp": ActorPresetInfo(
        decomp_path="actors/thwomp",
        level="wf",
        group="group1",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=88, enum="MODEL_THWOMP")],
            geolayout=201327176,
            c_name="thwomp_geo",
            displaylist=None,
        ),
        collision={
            "Thwomp": CollisionInfo(address=83933136, c_name="thwomp_seg5_collision_0500B7D0"),
            "Thwomp 2": CollisionInfo(address=83933484, c_name="thwomp_seg5_collision_0500B92C"),
        },
    ),
    "Toad": ActorPresetInfo(
        decomp_path="actors/toad",
        level="castle_inside",
        group="group15",
        animation=AnimInfo(
            address=100727880,
            behaviours={"End Toad": 318770824, "Toad Message": 318779128},
            size=8,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=[
                "Wave Then Run (West)",
                "Walking (West)",
                "Node Then Turn (East)",
                "Walking (East)",
                "Standing (West)",
                "Standing (East)",
                "Waving Both Arms (West)",
                "Waving One Arm (East)",
            ],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=221, enum="MODEL_TOAD")],
            geolayout=218104804,
            c_name="toad_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Tweester/Tornado": ActorPresetInfo(
        decomp_path="actors/tornado",
        level="ssl",
        group="group5",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=86, enum="MODEL_TWEESTER")], geolayout=83969584, c_name=None, displaylist=None
        ),
        collision={},
    ),
    "Transparent Star": ActorPresetInfo(
        decomp_path="actors/transperant_star",
        level="bbh",
        group="common1",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=121, enum="MODEL_TRANSPARENT_STAR")],
            geolayout=369102700,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
    "Treasure Chest": ActorPresetInfo(
        decomp_path="actors/treasure_chest",
        level="wdw",
        group="group13",
        animation={},
        models={
            "Treasure Chest Base": ModelInfo(
                model_id=[ModelIDInfo(number=101, enum="MODEL_TREASURE_CHEST_BASE")],
                geolayout=218104912,
                c_name=None,
                displaylist=None,
            ),
            "Treasure Chest Lid": ModelInfo(
                model_id=[ModelIDInfo(number=102, enum="MODEL_TREASURE_CHEST_LID")],
                geolayout=218104936,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Tree": ActorPresetInfo(
        decomp_path="actors/tree",
        level="bbh",
        group="common1",
        animation={},
        models={
            "Bubbly Tree": ModelInfo(
                model_id=[
                    ModelIDInfo(number=23, enum="MODEL_BOB_BUBBLY_TREE"),
                    ModelIDInfo(number=23, enum="MODEL_WDW_BUBBLY_TREE"),
                    ModelIDInfo(number=23, enum="MODEL_CASTLE_GROUNDS_BUBBLY_TREE"),
                    ModelIDInfo(number=23, enum="MODEL_WF_BUBBLY_TREE"),
                    ModelIDInfo(number=23, enum="MODEL_THI_BUBBLY_TREE"),
                ],
                geolayout=369102824,
                c_name=None,
                displaylist=None,
            ),
            "Pine Tree": ModelInfo(
                model_id=[ModelIDInfo(number=24, enum="MODEL_COURTYARD_SPIKY_TREE")],
                geolayout=369102848,
                c_name=None,
                displaylist=None,
            ),
            "(Unused) Pine Tree": ModelInfo(model_id=[], geolayout=369102896, c_name=None, displaylist=None),
            "Snow Tree": ModelInfo(
                model_id=[
                    ModelIDInfo(number=25, enum="MODEL_CCM_SNOW_TREE"),
                    ModelIDInfo(number=25, enum="MODEL_SL_SNOW_TREE"),
                ],
                geolayout=369102872,
                c_name=None,
                displaylist=None,
            ),
            "Palm Tree": ModelInfo(
                model_id=[ModelIDInfo(number=27, enum="MODEL_SSL_PALM_TREE")],
                geolayout=369102920,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Ukiki": ActorPresetInfo(
        decomp_path="actors/ukiki",
        level="ttm",
        group="group6",
        animation=AnimInfo(
            address=83974020,
            behaviours={"Ukiki": 318774448},
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=[
                "Run",
                "Walk (Unused)",
                "Apose (Unused)",
                "Death (Unused)",
                "Screech",
                "Jump Clap",
                "Hop (Unused)",
                "Land",
                "Jump",
                "Itch",
                "Handstand",
                "Turn",
                "Held",
            ],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=86, enum="MODEL_UKIKI")],
            geolayout=201326864,
            c_name="ukiki_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Unagi": ActorPresetInfo(
        decomp_path="actors/unagi",
        level="jrb",
        group="group4",
        animation=AnimInfo(
            address=83961892,
            behaviours=318787392,
            size=7,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Yawn", "Bite", "Swimming", "Static Straight", "Idle", "Open Mouth", "Idle 2"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=85, enum="MODEL_UNAGI")],
            geolayout=201326860,
            c_name="unagi_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Smoke": ActorPresetInfo(
        decomp_path="actors/walk_smoke",
        level="bbh",
        group="group0",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=150, enum="MODEL_SMOKE")],
            geolayout=385876024,
            c_name="smoke_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Warp Collision": ActorPresetInfo(
        decomp_path="actors/warp_collision",
        level="bbh",
        group="common1",
        animation={},
        models={},
        collision={
            "Door": CollisionInfo(address=50450040, c_name="door_seg3_collision_0301CE78"),
            "LLL Hexagonal Mesh": CollisionInfo(address=50450124, c_name="lll_hexagonal_mesh_seg3_collision_0301CECC"),
        },
    ),
    "Warp Pipe": ActorPresetInfo(
        decomp_path="actors/warp_pipe",
        level="bbh",
        group="common1",
        animation={},
        models=ModelInfo(
            model_id=[
                ModelIDInfo(number=73, enum="MODEL_BITS_WARP_PIPE"),
                ModelIDInfo(number=18, enum="MODEL_BITDW_WARP_PIPE"),
                ModelIDInfo(number=22, enum="MODEL_THI_WARP_PIPE"),
                ModelIDInfo(number=22, enum="MODEL_VCUTM_WARP_PIPE"),
                ModelIDInfo(number=22, enum="MODEL_CASTLE_GROUNDS_WARP_PIPE"),
            ],
            geolayout=369099656,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
    "Water Bomb": ActorPresetInfo(
        decomp_path="actors/water_bubble",
        level="bob",
        group="group3",
        animation={},
        models={
            "Water Bomb": ModelInfo(
                model_id=[ModelIDInfo(number=84, enum="MODEL_WATER_BOMB")],
                geolayout=201327368,
                c_name=None,
                displaylist=None,
            ),
            "Water Bomb's Shadow": ModelInfo(
                model_id=[ModelIDInfo(number=85, enum="MODEL_WATER_BOMB_SHADOW")],
                geolayout=201327400,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Water Mine": ActorPresetInfo(
        decomp_path="actors/water_mine",
        level="wdw",
        group="group13",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=179, enum="MODEL_WATER_MINE")],
            geolayout=218104564,
            c_name="water_mine_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Water Ring": ActorPresetInfo(
        decomp_path="actors/water_ring",
        level="wdw",
        group="group13",
        animation=AnimInfo(
            address=100745084,
            behaviours={"Water Ring (Jet Stream)": 318781264, "Water Ring (Manta Ray)": 13003798},
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Wobble"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=104, enum="MODEL_WATER_RING")],
            geolayout=218104852,
            c_name="water_ring_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Water Splash": ActorPresetInfo(
        decomp_path="actors/water_splash",
        level="bbh",
        group="group0",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=167, enum="MODEL_WATER_SPLASH")],
            geolayout=385876528,
            c_name="water_splash_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Water Wave": ActorPresetInfo(
        decomp_path="actors/water_wave",
        level="bbh",
        group="group0",
        animation={},
        models={
            "Idle Water Wave": ModelInfo(
                model_id=[ModelIDInfo(number=166, enum="MODEL_IDLE_WATER_WAVE")],
                geolayout=385876260,
                c_name=None,
                displaylist=None,
            ),
            "Water Wave Trail": ModelInfo(
                model_id=[ModelIDInfo(number=163, enum="MODEL_WAVE_TRAIL")],
                geolayout=385876328,
                c_name=None,
                displaylist=None,
            ),
        },
        collision={},
    ),
    "Whirlpool": ActorPresetInfo(
        decomp_path="actors/whirlpool",
        level="jrb",
        group="group4",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=87, enum="MODEL_DL_WHIRLPOOL")],
            geolayout=None,
            c_name=None,
            displaylist=DisplaylistInfo(address=83967160, c_name="whirlpool_seg5_dl_05013CB8"),
        ),
        collision={},
    ),
    "White Particle": ActorPresetInfo(
        decomp_path="actors/white_particle",
        level="bbh",
        group="common1",
        animation={},
        models={
            "White Particle": ModelInfo(
                model_id=[ModelIDInfo(number=160, enum="MODEL_WHITE_PARTICLE")],
                geolayout=369102744,
                c_name=None,
                displaylist=None,
            ),
            "White Particle (DL)": ModelInfo(
                model_id=[ModelIDInfo(number=158, enum="MODEL_WHITE_PARTICLE_DL")],
                geolayout=None,
                c_name=None,
                displaylist=DisplaylistInfo(address=50514080, c_name="white_particle_dl"),
            ),
        },
        collision={},
    ),
    "White Particle Small": ActorPresetInfo(
        decomp_path="actors/white_particle_small",
        level="bbh",
        group="group0",
        animation={},
        models={
            "White Particle Small": ModelInfo(
                model_id=[ModelIDInfo(number=164, enum="MODEL_WHITE_PARTICLE_SMALL")],
                geolayout=None,
                c_name=None,
                displaylist=DisplaylistInfo(address=67316248, c_name="white_particle_small_dl"),
            ),
            "(Unused) White Particle Small": ModelInfo(
                model_id=[],
                geolayout=None,
                c_name=None,
                displaylist=DisplaylistInfo(address=67316272, c_name="white_particle_small_unused_dl"),
            ),
        },
        collision={},
    ),
    "Whomp": ActorPresetInfo(
        decomp_path="actors/whomp",
        level="bob",
        group="group14",
        animation=AnimInfo(
            address=100796932,
            behaviours=318778316,
            size=2,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Walk", "Jump"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=103, enum="MODEL_WHOMP")],
            geolayout=218104960,
            c_name="whomp_geo",
            displaylist=None,
        ),
        collision=CollisionInfo(address=100796940, c_name="whomp_seg6_collision_06020A0C"),
    ),
    "Wiggler Body": ActorPresetInfo(
        decomp_path="actors/wiggler_body",
        level="thi",
        group="group11",
        animation=AnimInfo(
            address=83937396,
            behaviours=318785760,
            size=1,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Walk"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=88, enum="MODEL_WIGGLER_BODY")],
            geolayout=83937144,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
    "Wiggler Head": ActorPresetInfo(
        decomp_path="actors/wiggler_head",
        level="thi",
        group="group11",
        animation=AnimInfo(
            address=83946636,
            behaviours=318785688,
            size=1,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Walk"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=87, enum="MODEL_WIGGLER_HEAD")],
            geolayout=201326640,
            c_name="wiggler_head_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Wooden Signpost": ActorPresetInfo(
        decomp_path="actors/wooden_signpost",
        level="bbh",
        group="common1",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=124, enum="MODEL_WOODEN_SIGNPOST")],
            geolayout=369102772,
            c_name=None,
            displaylist=None,
        ),
        collision=CollisionInfo(address=50519424, c_name="wooden_signpost_seg3_collision_0302DD80"),
    ),
    "Yellow Sphere (Bowser 1)": ActorPresetInfo(
        decomp_path="actors/yellow_sphere",
        level="bowser_1",
        group="group12",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=3, enum="MODEL_LEVEL_GEOMETRY_03")],
            geolayout=218103984,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
    "Yellow Sphere": ActorPresetInfo(
        decomp_path="actors/yellow_sphere_small",
        level="wf",
        group="group1",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=85, enum="MODEL_YELLOW_SPHERE")],
            geolayout=201326592,
            c_name="yellow_sphere_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "Yoshi": ActorPresetInfo(
        decomp_path="actors/yoshi",
        level="castle_grounds",
        group="group10",
        animation=AnimInfo(
            address=84034024,
            behaviours=318784824,
            size=None,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Idle", "Walk", "Jump"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=85, enum="MODEL_YOSHI")],
            geolayout=201327720,
            c_name="yoshi_geo",
            displaylist=None,
        ),
        collision={},
    ),
    "(Unused) Yoshi Egg": ActorPresetInfo(
        decomp_path="actors/yoshi_egg",
        level="wf",
        group="group1",
        animation={},
        models=ModelInfo(
            model_id=[ModelIDInfo(number=87, enum="MODEL_YOSHI_EGG")],
            geolayout=201327076,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
    "Castle Flag": ActorPresetInfo(
        decomp_path="levels/castle_grounds/areas/1/11",
        level="CG",
        group=None,
        animation=AnimInfo(
            address=117492060,
            behaviours=318782552,
            size=1,
            ignore_bone_count=False,
            dma=False,
            directory=None,
            names=["Wave"],
        ),
        models=ModelInfo(
            model_id=[ModelIDInfo(number=55, enum="MODEL_CASTLE_GROUNDS_FLAG")],
            geolayout=234882656,
            c_name=None,
            displaylist=None,
        ),
        collision={},
    ),
}
