name: Tests

on: [push, pull_request]

jobs:
  tests:
    permissions: {} # Remove all permissions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11" # Blender 4.2 ships 3.11
      - name: Run tests that do not need Blender
        run: python tests/run_tests.py
